### ISSUE TITLE
Drawer is shown fully transparent when using with Crosswalk WebView

### ISSUE THREAD

**Issue by roher-roher** [mikepenz/MaterialDrawer#1439] opened 2016-08-03 09:01 UTC
Hello! I have a strange problem with MaterialDrawer.
I use [Crosswalk](https://crosswalk-project.org/) Webview together with MaterialDrawer in my activity:
```java
import ...;
import com.mikepenz.materialdrawer.Drawer;
import com.mikepenz.materialdrawer.DrawerBuilder;
import com.mikepenz.materialdrawer.model.PrimaryDrawerItem;
import com.mikepenz.materialdrawer.model.SectionDrawerItem;
import com.mikepenz.materialdrawer.model.interfaces.IDrawerItem;

import org.xwalk.core.JavascriptInterface;
import org.xwalk.core.XWalkActivity;
import org.xwalk.core.XWalkResourceClient;
import org.xwalk.core.XWalkView;

public class MainActivity extends XWalkActivity {

    private XWalkView webView;
    private Drawer drawer;
    
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        webView = (XWalkView) findViewById(R.id.xwvMain);
        webView.setResourceClient(new MyResourceClient(webView,
                getPackageManager()));
        drawer = new DrawerBuilder()
                .withActivity(this)
                .withSystemUIHidden(true)
                .withOnDrawerListener(new DrawerListener())
                .withOnDrawerItemClickListener(
                        new DrawerItemClickListener(this))
                .withSelectedItem(0)
                .addDrawerItems(
                        new PrimaryDrawerItem()
                                .withName(R.string.action_main_screen)
                                .withIcon(R.drawable.ic_fullscreen_black_24dp)
                                .withIdentifier(0),
                        new PrimaryDrawerItem()
                                .withName(R.string.action_technical_info_screen)
                                .withIcon(R.drawable.ic_info_black_24dp)
                                .withIdentifier(1),
                        new PrimaryDrawerItem()
                                .withName(R.string.action_settings)
                                .withIcon(R.drawable.ic_settings_black_24dp)
                                .withIdentifier(2),
                        new SectionDrawerItem()
                                .withName(R.string.action_actions),
                        new PrimaryDrawerItem()
                                .withName(R.string.action_restart_service)
                                .withIcon(R.drawable.ic_refresh_black_24dp)
                                .withIdentifier(3),
                        new PrimaryDrawerItem()
                                .withName(R.string.action_shutdown_service)
                                .withIcon(R.drawable.ic_close_black_24dp)
                                .withIdentifier(4),
                        new PrimaryDrawerItem()
                                .withName(R.string.action_restart_adapter)
                                .withIcon(R.drawable.ic_memory_black_24dp)
                                .withIdentifier(5)).build();

        drawer.addStickyFooterItem(new PrimaryDrawerItem()
                .withName(R.string.footer_go_to_website)
                .withIcon(R.drawable.ic_link_black_24dp).withIdentifier(10));
        drawer.addStickyFooterItem(new PrimaryDrawerItem()
                .withName(R.string.footer_translate)
                .withIcon(R.drawable.ic_translate_black_24dp)
                .withIdentifier(11));

        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            drawer.getDrawerLayout().setFitsSystemWindows(false);
        }
    }

    ...
}
```
On Android 4 it works ok, but on Android 5 and 6 the drawer is not visible when I slide from the left. But I know that all drawer items work because when I click on the area where the drawer should be, the corresponding item click event is fired. And moreover, after I click on this invisible drawer for the first time, it becomes visible until I quit the activity. When I open the activity again, it becomes invisible until first click on it again. Please watch this video for the demonstation: https://www.youtube.com/watch?v=OOIdYsbRz0A

The bug is somehow connected with Crosswalk, because on my second activity, which doesn't use webview, the drawer works ok.

Any help will be appreciated, and if some more info is needed, I'm ready to provide it.

**Comment by mikepenz** [comment] 2016-08-03 09:03
@roher-roher I expect this to be a platform bug related to the `DrawerLayout` from the support libs, which I can't control

**Comment by roher-roher** [comment] 2016-08-03 09:26
Well, that's bad news. The point is that I can't find anything this issue in Google, so looks like I'm the only one experiencing this (together with the users of my app of course).

Anyway, thanks for the answer.

**Comment by mikepenz** [comment] 2016-08-03 13:49
any issue on the `Crosswalker` with the `DrawerLayout`? You might also be able to just try it with a plain empty `DrawerLayout` if it also occurs?

**Comment by roher-roher** [comment] 2016-08-03 15:17
Yes, I will try. If it will be the same, I will post an issue to Crosswalk.

**Comment by mikepenz** [comment] 2016-08-03 17:38
@roher-roher ok thanks. please report back afterwards. (if it only occurs with the `MaterialDrawer` please provide a small sample app so I can debug this issue)

I close this for the time being and wait for further feedback.

**Comment by roher-roher** [comment] 2016-08-11 15:15
Hi!
Surprisingly, but the issue occurs only with MaterialDrawer.
Attached archives with 2 apks and Android Studio projects - one using DrawerLayout, the other using MaterialDrawer:
[DrawerLayout.zip](https://github.com/mikepenz/MaterialDrawer/files/413532/DrawerLayout.zip)
[MaterialDrawer.zip](https://github.com/mikepenz/MaterialDrawer/files/413531/MaterialDrawer.zip)

Testcases are the following:
TC1:
1. Kill the app from the System Settings if it was running before;
2. Launch the app;
3. Try opening navigation drawer by swiping from the left immediately, before splash screen is gone and "Hello world!" text is displayed.
ER: Navigation drawer has opened and visible.
AR for DrawerLayout: = ER, drawer has opened successfully and visible.
AR for MaterialDrawer: = ER, drawer has opened successfully and visible.

TC2:
1. Launch the app;
2. Wait till the splash screen is gone and "Hello world!" text is displayed;
3. Try opening navigation drawer by swiping from the left.
ER: Navigation drawer has opened and visible.
AR for DrawerLayout: = ER, drawer has opened successfully and visible.
AR for MaterialDrawer: drawer has opened invisibly and is shown only if you click on the area where it should be.

So, as you can see, before CrossWalk WebView is initialized and shown (splash screen is displayed during initializing), both implementations work correct. But as soon as WebView is shown, only DrawerLayout works.

**Comment by mikepenz** [comment] 2016-08-11 19:14
@roher-roher interesting enough it is related to the:
```java
        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            drawer.getDrawerLayout().setFitsSystemWindows(false);
        }
```

If you remove it it works properly, but you get the blue bar on top. 

I also tested the normal `DrawerLayout` but it has some worse behavior than the `MaterialDrawer` with crosswalk. 

I am sure it is a general `DrawerLayout` + `fitsSystemWindow`s + `WebView` problem, which I can't solve :/

**Comment by roher-roher** [comment] 2016-08-15 14:49
Thanks!
So, it looks like there is no way to make my app truly fullscreen if I use Drawer + Crosswalk?

**Comment by mikepenz** [comment] 2016-08-15 17:11
@roher-roher it seems so. There might be other possibilities to achieve this. Probably wrapping everything into a `ScrimInsetsFrameLayout` and preventing the default `fitsSystemWindow`s behavior.

**Closed** 2016-08-15 17:11 UTC
Labels: question

**Comment by roher-roher** [comment] 2016-08-16 14:12
Hmm, but I've just noticed that I don't use this code:
`if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
   drawerLayout.setFitsSystemWindows(false);
}`
in the DrawerLayout variant. And it works well together full-screen mode.

I've also tried ScrimInsetsFrameLayout with MaterialDrawer and without that code, and it has exactly the same behaviour :-(

**Comment by mikepenz** [comment] 2016-08-16 14:24
@roher-roher I had quite a lot of lag, and ui issues with the `DrawerLayout` variant.

**Comment by roher-roher** [comment] 2016-08-16 14:52
@mikepenz, even when I completely remove all fullscreen-related stuff, the drawer is still drawn behind the webview:
[MainActivity.txt](https://github.com/mikepenz/MaterialDrawer/files/420528/MainActivity.txt)

**Comment by roher-roher** [comment] 2016-08-16 15:05
Done the same with DrawerLayout - everything works like a charm:
[MainActivity.txt](https://github.com/mikepenz/MaterialDrawer/files/420569/MainActivity.txt)

**Comment by mikepenz** [comment] 2016-08-16 18:50
Hmm it's weird, as it will work for me with the `MaterialDrawer` and I can't reproduce the behavior of it being behind the `WebView` 

which android version are you on?

[drawer.zip](https://github.com/mikepenz/MaterialDrawer/files/421065/drawer.zip)

**Comment by roher-roher** [comment] 2016-08-16 18:55
I'm using Android 6.0.1, the device is Samsung Galaxy Note 4.

**Comment by roher-roher** [comment] 2016-08-18 10:25
Hi @mikepenz!
Any thoughts?

**Comment by mikepenz** [comment] 2016-08-18 10:49
have you tried the projects I sent to you? I can't reproduce it with them.

**Comment by roher-roher** [comment] 2016-08-18 14:59
Your code and mine are absolutely the same (if not taking comments into account). I don't believe in miracles, but I've tried your code, and of course the issue has reproduced.

**Comment by mikepenz** [comment] 2016-08-18 15:04
@roher-roher me neither. Hmmm so it is a combination of the `fitsSystemWindow`s flag, und the Android version in addition... :/

**Comment by roher-roher** [comment] 2016-08-18 15:07
But why does it work good with the standard DrawerLayout? :)

**Comment by roher-roher** [comment] 2016-08-18 15:12
I am ready to provide any help if I can. Maybe try to download source code of MaterialDrawer and debug? But I don't know what to search :(

**Comment by mikepenz** [comment] 2016-08-18 15:44
@roher-roher I have another idea which might work, and may end your troubles. 

Creating the `DrawerLayout` as you do in the normal sample. And just using the view of the `MaterialDrawer`. Maybe the inflating is causing troubles in combination with the `WebView` (in comparison to the default which already has the `DrawerLayout` in the `xml`)

So you will have something like this (to simplify I just removed everything which is not really necessary to share the code :D):
```java
public class MainActivity extends XWalkActivity {

    private LinearLayout lvDrawer;
    private XWalkView webView;
    private Drawer drawer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);
        lvDrawer = (LinearLayout) findViewById(R.id.lvDrawer);
        webView = (XWalkView) findViewById(R.id.xwvMain);

        setupDrawer();
    }

    @Override
    protected void onXWalkReady() {
        webView.load("file:///android_asset/index.html", null);
    }

    private void setupDrawer() {
        drawer = new DrawerBuilder()
                .withActivity(this)
                //remove this if it should go velow the statusBar
                .withDisplayBelowStatusBar(false)
                .withSelectedItem(0)
                .addDrawerItems(/*your items*/)
                .buildView();

        lvDrawer.addView(drawer.getSlider());
    }
}
```

and change the `ListView` in the layout to:
```xml
<LinearLayout
        android:id="@+id/lvDrawer"
        android:layout_width="240dp"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:background="#aaa"/>
```

**Comment by roher-roher** [comment] 2016-08-18 16:03
@mikepenz, thanks for the idea but it didn't help - the drawer is still drawn behind the webview, the only change is that it's top edge is now below the notification bar.

**Comment by mikepenz** [comment] 2016-08-18 17:21
then I am really out of ideas. Because with the above it uses a normal `DrawerLayout` coming from the `xml` and just the content is filled with a `RecyclerView` containing the `Item`s

**Comment by roher-roher** [comment] 2016-08-18 18:21
Me too :/ Maybe you set some specific flags during inflating the RecyclerView?
JFI: I also tried `drawer.getDrawerLayout().bringToFront()` and it didn't help.

**Comment by roher-roher** [comment] 2016-08-19 13:00
Hi @mikepenz! I found out a very interesting thing - this is the line of code that makes everything work as needed in the classic `DrawerLayout` example:
```
lvDrawer.setAdapter(new ArrayAdapter<String>(this,
                android.R.layout.simple_list_item_1, new String[]{"One", "Two", "Three"}));
```

How did I come up to it:
I wanted to find out what exactly in your library makes the drawer be drawn behind the WebView and started removing lines one by one from the `setupDrawer()` method, and finally ended up with removing the whole method completely. The drawer still opened behind the WebView...
Then I though:
> If your library is not forcing the drawer to be behind the WebView, as I removed setup of `MaterialDrawer` completely, then something in the classic `DrawerLayout` code is forcing it to be in front of the WebView.

So I began, again line by line, transforming the code to the classic example. First I replaced
```
<LinearLayout
    android:id="@+id/llDrawer"
    android:layout_width="240dp"
    android:layout_height="match_parent"
    android:layout_gravity="start"
    android:background="#aaa"
    android:orientation="vertical"/>
```
back to
```
<ListView
    android:id="@+id/lvDrawer"
    android:layout_width="240dp"
    android:layout_height="match_parent"
    android:layout_gravity="start"
    android:background="#aaa"
    android:choiceMode="singleChoice"
    android:divider="@android:color/transparent"
    android:dividerHeight="0dp"/>
```
and nothing changed.
After that I added these lines to my activity:
```
private ListView lvDrawer;
...
lvDrawer = (ListView) findViewById(R.id.lvDrawer);
```
and checked again - the drawer was still behind the WebView.

And finally I placed this line into `onCreate`:
```
lvDrawer.setAdapter(new ArrayAdapter<String>(this,
                android.R.layout.simple_list_item_1, new String[]{"One", "Two", "Three"}));
```
And Voila! The drawer started displaying correclty!!!

**Comment by roher-roher** [comment] 2016-08-19 13:43
Trying to figure out how can I use this information...

**Comment by mikepenz** [comment] 2016-08-20 11:59
@roher-roher seems like the `setAdapter` somehow causes a redraw of the slider which brings it to the frong. 

Perhaps the difference from `ListView` and `RecyclerView` make some additional differen :/

I am really out of ideas. As the whole slider is still managed by the `DrawerLayout` which is from Google

**Comment by homer-jay** [comment] 2017-05-05 08:18
I can confirm this is happening to me as well with the regular DrawerLayout from the support library (v25.3.1) and a XWalk web view.

**Comment by mikepenz** [comment] 2017-05-05 08:53
@homer-jay thank you for the info. Then there's nothing this library will change about it :(

**Comment by KimiChao** [comment] 2017-05-15 07:27
This will be work for your guys.

`drawerLayout.bringChildToFront(drawerView);
drawerLayout.requestLayout();`

**Comment by mylab4492** [comment] 2018-01-10 06:32
Use toolbar.bringToFront();

**Comment by SkyZero1228** [comment] 2019-11-11 00:04
@KimiChao 
Its not working too, 

Is there anyone who found the good solution?
