### ISSUE TITLE
setSelection not showing the item background

### ISSUE THREAD

**Issue by kuba2k2** [mikepenz/MaterialDrawer#2574] opened 2020-03-24 12:56 UTC
## About this issue

When MaterialDrawerSliderView.setSelection() is called, the selected item has no blue background. The same goes for the MiniDrawer - clicking an item in MiniDrawer selects it, changes the item's text color but does not display the background.

The same issue was closed in the previous year, #2502.

You can quickly check this in the sample app (i.e. version 8.0.0-rc01). One way is to go to the MiniDrawer demo activity and then press an item in minidrawer. The second is for example in the DrawerActivity - just add a button and `slider.setSelection(2002)` when the button is clicked. The background is then gone.

https://streamable.com/x94ox
In this example the item with ID 2002 is set to be selected. This works but has no background. Manually changing to another item and back to 2002 restores the background.

The same goes for the mini drawer (calling `sliderView.setSelection(1)`).
https://streamable.com/8s6yw

There is a possible fix, to which I'll probably stick right now in my app, but I believe this is not a proper solution, thus waiting for you because you know the library better.
Try to change the line 772 of MaterialDrawerSliderView.kt (`select.deselect()` in `setSelection()`) to something like
`select.deselectByIdentifiers(select.selectedItems.map { it.identifier }.toSet())`
Then everything starts to work as intended, unless you click my "set selection" button few times quickly, then the BG is gone again. I think this is an issue of updating the items too quickly (`select.deselect()` updates/deselects every item in the drawer, that's where the problem happens - clicking the item manually updates just the clicked and previously selected one).

I hope this is a clear explanation of the problem.
Thanks in advance

## Details
- [8.0.0-rc01] Used library version
- [androidX appcompat 1.1.0] Used support library version
- [3.5.3] Used gradle build tools version
- [AS 4.0 Canary 9] Used tooling / Android Studio version
- [none - just the sample app] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment] 2020-03-24 17:03
@kuba2k2 can you try to disable: `isSelectedBackgroundAnimated` 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/AbstractDrawerItem.kt#L99

**Comment by kuba2k2** [comment] 2020-03-24 17:12
Sure. Then the background shows correctly for those items which have animation disabled.

**Comment by mikepenz** [comment] 2020-03-24 17:14
It is kind of a long lasting bug, and kind of related to the built in animation when changing states :/ 

I am honestly not 100% sure if it is easily resolvable inside the library or if it is a bug the way we assume that state changes should animate :/

**Comment by mikepenz** [comment] 2020-03-28 10:37
I think this issue can be closed as based on the following code this is fully out of our control, and only depends on the systems behavior to animate state changes:

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDescribeableDrawerItem.kt#L53-L54

And the animation property for the `StateListDrawable`:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUtils.kt#L383-L387
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUtils.kt#L396-L400

2 suggestions here:
- disable animating state changes
- enable to update the items on change (e.g. not only state adjustment, but full new bind of the `RecyclerView` item)

**Comment by DeweyReed** [comment] 2020-04-01 14:17
I'm upgrading from `7.0.0-beta01` to 8.0.0 and facing the same issue. Selections during initialization (activity's onCreate) work as expected but later selections don't.

I can reproduce the problem by setting a click listener:

```Kotlin
slider.onDrawerItemClickListener = { v, item, position ->
    slider.setSelectionAtPosition(position, false)
    false
}
```

Similarly, I reproduce the same look by directly accessing `SelectExtension`:

```Kotlin
slider.onDrawerItemClickListener = { v, item, position ->
	slider.selectExtension.run {
	    deselect()
	    select(position)
	}
    false
}
```

If I remove `deselect()`, things start to work so I think this issue may have something to do with those `RecyclerView` updates stuff.

**Comment by mikepenz** [comment] 2020-04-04 13:49
Please see the above comment: https://github.com/mikepenz/MaterialDrawer/issues/2574#issuecomment-605428918 @DeweyReed 

if you try to disable animations for the background state change would it work? 

if yes then I am almost certain there is a bug in the android system whereas a state change does not properly trigger the `StateListDrawable` update :/

**Comment by DeweyReed** [comment] 2020-04-05 03:19
@mikepenz `isSelectedBackgroundAnimated = false` works.

I use `setSelection` without `fireEvent`. Another fix I found is 

```Kotlin
val fastAdapter = adapter
for (index in 0 until fastAdapter.itemCount) {
    val item = fastAdapter.getItem(index) ?: continue
    val isTarget = item.identifier == targetIdentifier
    if (item.isSelected != isTarget) {
        item.isSelected = isTarget
        fastAdapter.notifyItemChanged(index)
    }
}
```

So I suspect that the problem is because `RecyclerView` updates too much and then Android system may be unable to properly handle `StateListDrawable`'s changes like you said.

**Comment by mikepenz** [comment] 2020-04-05 10:30
@DeweyReed there's an alternative to your code though. the `FastAdapter` offers an API to do this directly. Just enable the flag `selectWithItemUpdate` on the `SelectExtension` of the `FastAdapter` 

some (non beautiful) demo code :D
![image](https://user-images.githubusercontent.com/1476232/78472449-24a73300-7739-11ea-9ab2-4a0023433c3c.png)

Hope this helps and resolves this topic :)

**Closed by mikepenz** 2020-04-05 10:30 UTC
Labels: question

**Comment by Kashish-Sharma** [comment] 2020-04-12 12:21
> @kuba2k2 can you try to disable: `isSelectedBackgroundAnimated`
> 
> https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/AbstractDrawerItem.kt#L99

This works!
