### ISSUE TITLE
Confusing mix of relative and global positions when removing/adding elements

### ISSUE THREAD

**Issue by Strayer** [mikepenz/MaterialDrawer#1037] opened 2016-02-25 09:49 UTC
I recently had to implement a function that updates expandable menu items in the drawer. While implementing this functionality I got horribly confused about what a position actually means.

(warning, the following code snippets are basically pseudo-code from my memory... but I guess it will suffice get my point across :) )

I'm using the `getAdapterPosition(IDrawerItem instance)` method to find a headline that marks the "start point" for the dynamic menu entries, the `remove(int position)` method to remove all already existing drawer items of those dynamic items and then the `add(List<IDrawerItem> items, int position)` method to add new items.

I was having multiple issues with strange placement of these items until I noticed something about global and relative positions in the JavaDoc and Issue #990 ...

Right now, to remove an item I have to do this:
`drawerItemAdapter.remove(drawerItemAdapter.getGlobalPosition(drawerItemAdapter.getAdapterPosition(drawerItem)))`

The same has to be done when adding new elements:
```
int headlinePos = drawerItemAdapter.getAdapterPosition(headlineDrawerItem);
drawerItemAdapter.add(listOfNewItems, drawerItemAdapter.getGlobalPosition(headlinePos + 1));
```

Is this the correct way to do this? I guess a getGlobalPosition(IDrawerItem) would be enough to make this less confusing, but maybe I'm just missing something...

**Comment by mikepenz** [comment] 2016-02-27 16:29
@Strayer thanks for your detailed issue. 

The behavior of this has changed starting with v5.0.0. The root cause for this is the switch from built in adapter to the `FastAdapter`. So you may ask why I have decided to go with this. 

The main point is that I wanted consistency between the position you get from the listeners and the positions you have to pass if you want to modify something. 

So why will the first item be at position 1 if there is a header, and 0 if there is none? Yeah that comes because the `Header` is also just an item within the `RecyclerView` 

The internal structure looks like this. 
`HeaderAdapter`
`ItemAdapter` 
`FooterAdapter`
--------
`StickyFooterArea` (completely out of scope of the RV)

So the count of items of the header will count up the positions in the normal `ItemAdapter` and also in the `FooterAdapter` 

As you already correctly foudn the `getGlobalPosition()` method. It basically checks the position of the adapter you are calling it on (Theoretically there could be more as 3 (as it is the case for the drawer)) and will then add the number of items before the current adapter, so you can work with relative positions. 

I hope this clears up your confusion a bit :)

**Closed by mikepenz** 2016-02-27 16:29 UTC
Labels: good to know, question
