### ISSUE TITLE
itemsClicks still hapen when drawer is close. What can be caused this? 

### ISSUE THREAD

**Issue by ibado** [mikepenz/MaterialDrawer#2017] opened 2017-09-01 18:58 UTC
![print_close](https://user-images.githubusercontent.com/12547621/29983887-34aba6f0-8f2e-11e7-9e1d-5c5a1ca28a17.png)
![print_open](https://user-images.githubusercontent.com/12547621/29983892-3986f698-8f2e-11e7-8c3d-57c6c927efbd.png)

**Comment by mikepenz** [comment] 2017-09-01 19:45
Is this a duplicate of: https://github.com/mikepenz/MaterialDrawer/issues/2016 ?

**Comment by mikepenz** [comment] 2017-09-03 17:07
@ibado the problem is that the way the `SlidingPaneLayout` works, the view which is crossfaded is not gone. 

Is it possible that you make the content area on the right clickable, so it will catch the touch? It should be in the front of that non visible drawer view

**Comment by ibado** [comment] 2017-09-04 12:22
I set propperty clickeable=false to the fragment in the front but seems doesn't work. :/ Also i will try setting a click to de fragment background and do nothing but that didn't work

**Comment by mikepenz** [comment] 2017-09-28 16:56
@ibado did you find something related to this issue already?

**Comment by mikepenz** [comment] 2018-02-04 14:32
Closing this now :(. 
No more comment or progress were made in here. 

Please let me know if you figured something. or if there is some action we can do to solve this ...

**Closed by mikepenz** 2018-02-04 14:32 UTC
Labels: question
