### ISSUE TITLE
Drawer item selection not working properly

### ISSUE THREAD

**Issue by despDev** [mikepenz/MaterialDrawer#879] opened 2015-12-15 04:15 UTC
I'm trying to set selection in  activity onRestart method by doing mDrawer.setSelection(identifier);  
And newly selected item has icon without tint but the old item icon still tinted.
All item were created withIconTintingEnabled(true). 

![screen_bug](https://cloud.githubusercontent.com/assets/9020678/11801937/26b1cbc0-a2f3-11e5-9f8b-515e92e56050.jpg)

**Comment by mikepenz** [comment] 2015-12-15 07:43
@despDev are those icon from `Android-Iconics`? Or drawables?

**Comment by despDev** [comment] 2015-12-15 11:09
@mikepenz All icons are drawables created through http://romannurik.github.io/AndroidAssetStudio/

**Comment by despDev** [comment] 2015-12-15 18:40
Also worth mentioning that version 3.0.8 works perfectly. Item selection is correct. Much more smoother animation on closing drawer. Nice ripple effect when selection items on post Lollipop devices. Current version has no ripple effect on item selection instead there is some weird blinking. Tested on 3 physical devices.

**Comment by mikepenz** [comment] 2015-12-15 19:23
@despDev there is no more ripple because google apps also do not have it. 
regarding animation when closing. i lowered the amount of delay for the close. You can modify this value via the builder. 
v3.0.8 uses a `ListView` which handles the selections different. 

The above issue happens with the latest version?

**Comment by despDev** [comment] 2015-12-15 19:34
@mikepenz Yes. Above issue happens with the latest version. And thanks for the explanation.

**Comment by mikepenz** [comment] 2015-12-15 22:08
@despDev could you please provide a small sample app which reproduces this issue? so i can debug and test what could cause the problem?

**Comment by despDev** [comment] 2015-12-16 09:18
@mikepenz Ofcourse, as soon as i can.

**Comment by mikepenz** [comment] 2015-12-16 09:19
@despDev thank you so much. that really helps a lot :+1:

**Comment by mikepenz** [comment] 2015-12-16 19:53
@despDev i answered your mail :)

**Closed by mikepenz** 2015-12-16 19:53 UTC
Labels: question
