### ISSUE TITLE
Problem with selection in minidrawer

### ISSUE THREAD

**Issue by Raffaa** [mikepenz/MaterialDrawer#2688] opened 2020-12-07 17:17 UTC
## About this issue

- Hi, I made a custom implementation of MiniDrawerItem integrating also NavigationItem. The problem is that the selection isn't working properly. In particular the selection logic seems to work fine but is the view itself that isn't updating.
The scenario is that when I select an Item i want the drawable icon to change color, in the expanded view all seems to work properly, in the collapsed one the view do not change color.
- https://github.com/Raffaa/MaterialDrawerTestRepo

## Details
- [8.2.0] Used library version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)

**Comment by mikepenz** [comment] 2020-12-07 17:21
@Raffaa you mean you implemented a custom `MiniDrawerItem`? How does it react to selection changes? Do you have a `StateListDrawable`? 

If not you may have to enable `selectWithItemUpdate` in the `SelectExtension` https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/select/SelectExtension.kt#L52

**Comment by Raffaa** [comment] 2020-12-07 17:48
> @Raffaa you mean you implemented a custom `MiniDrawerItem`? How does it react to selection changes? Do you have a `StateListDrawable`?
> 
> If not you may have to enable `selectWithItemUpdate` in the `SelectExtension` https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/select/SelectExtension.kt#L52

Hi mike, yeah I mean MiniDrawerItem, I provided a test project made up really really quickly so there might be some stupid errors (😄 ) but the problem is reproduced. I will dig into this "problem" in the next days

**Comment by Raffaa** [comment] 2020-12-09 16:36
I made some tests, form my trials it came up that bindView is called only on the miniItem selected (the "PrimaryItem"'s bindView is called on all elements correctly). 
I also tried to set selectWithItemUpdate to true but nothing changed.

**Comment by mikepenz** [comment] 2020-12-18 09:44
@Raffaa so I looked further into this and it looks like the problem is related to the `NavController` setup. The `performNavigation` will consume the event and no longer forward it to the mini drawer. 

I'll see to provide an updated release with a fix for this

**Closed** 2020-12-18 09:58 UTC
Labels: question

**Comment by Raffaa** [comment] 2020-12-18 13:42
Hi @mikepenz now it works, thanks!!
I noticed two little bugs:

- With version 8.3.0 the _closeOnClick_ property of the drawer layout won't work with miniDrawer. This because now to keep the drawers synced you call setSelection also on minidrawer, which calls the cossfader.crossfade. I think this is easily fixable by adding a simple check in the [setSelection] (don't know if this can produce some side effects)(https://github.com/mikepenz/MaterialDrawer/blob/16db678c7713058074a0cadf69470d010b2f3acb/library/src/main/java/com/mikepenz/materialdrawer/widget/MiniDrawerSliderView.kt#L240) method of the minidrawer:
```    
fun onItemClick(selectedDrawerItem: IDrawerItem<*>): Boolean {
        //We only need to clear if the new item is selectable
        return if (selectedDrawerItem.isSelectable) {
            //crossfade if we are cross faded
            crossFader?.let {
                if (drawer?.closeOnClick != false && it.isCrossfaded) {
                    it.crossfade()
                }
            }
            //update everything
            if (selectedDrawerItem.hiddenInMiniDrawer) {
                selectExtension.deselect()
            } else {
                setSelection(selectedDrawerItem.identifier)
            }

            false
        } else {
            true
        }
    }
```

- The mini drawer selection now work as expected (the icon change color) the only problem is that when I close the expanded drawer. In fact only when changing from "exapnded drawer" to minidrawer, the minidrawer icon of the selected item will be colored as non selected. Of course if I select other icons afterwards, they will color correctly. I didn't have much time to look at this problem in detail.

**Comment by mikepenz** [comment] 2020-12-18 14:27
I will follow up on the first little bug you mentioned. 

The second thing seems to may result from the tinting. be careful when using the same drawable for multiple views, with tinting. usually you should mutate all of them and try to have unique states for all of them, otherwise they may affect each other

**Comment by Raffaa** [comment] 2020-12-21 11:35
> I will follow up on the first little bug you mentioned.
> 
> The second thing seems to may result from the tinting. be careful when using the same drawable for multiple views, with tinting. usually you should mutate all of them and try to have unique states for all of them, otherwise they may affect each other

I didn't quite catch what you mean by _"The second thing seems to may result from the tinting."_. I treid to set isIconTinted to false and with this disabled when corssfading the color is mantained correctly but then it wont work the color change on the selection. Here's a video of the _"problem"_: [GDrive Link](https://drive.google.com/file/d/1SPIC5T55RoCGMPZ8iNUVV_x_vUaGs0bV/view)

**Comment by mikepenz** [comment] 2020-12-21 11:44
I'd suggest you to cleanup your items as much as possible, most of the flexible tinting, ... stuff is not really relevant for your usecase as those things are only in the items for the super flexible API the library has to offer. 

in your project I think you can eliminate most of these things. 

The video looks to me like a shared drawable state is causing this, or some wrong state itself of the view. 

---


the provided default items update the colors based on the view state using the android default state mechanisms and it fully depends on those to do their job :/

**Comment by Raffaa** [comment] 2020-12-21 14:36
> I'd suggest you to cleanup your items as much as possible, most of the flexible tinting, ... stuff is not really relevant for your usecase as those things are only in the items for the super flexible API the library has to offer.
> 
> in your project I think you can eliminate most of these things.
> 
> The video looks to me like a shared drawable state is causing this, or some wrong state itself of the view.
> 
> the provided default items update the colors based on the view state using the android default state mechanisms and it fully depends on those to do their job :/

Also the default items in my project have the same behavior, I tried to clean all my modifications and also then I was having the same issue. Then I changed the valorization of the icon, in particular I changed 
```icon = ImageHolder(AppCompatResources.getDrawable(requireContext(), R.drawable.whatever))``` 
to 
```iconRes = R.drawable.whatever```

 and all seem working as expected

Thank you for your precious support 👍
