### ISSUE TITLE
After resuming opening a drawer in multi drawer mode doesn't close the other drawer

### ISSUE THREAD

**Issue by Thorsten1976** [mikepenz/MaterialDrawer#935] opened 2016-01-15 15:06 UTC
* Open one of two drawers in multi drawer mode (left drawer)
* Open the opposite drawer (Gravity.END; right drawer): the other drawer closes automatically.
* Open one drawer again.
* Bring the app in the background (e. g. by using the home button, app switcher) and the drawer still open
* After resuming the app, the mechanism that closes the other drawer automatically doesn't work anymore... both drawers a shown side by side

**Comment by mikepenz** [comment] 2016-01-15 15:38
@Thorsten1976 this seems to be a `DrawerLayout` issue, as the closing is not handling on my side for this. Perhaps you can try it with a plain `DrawerLayout` without a library. If it happens too you should open an issue for this on the official bug tracker:
https://code.google.com/p/android/issues/list

I can't reproduce this on my phone with the sample app.

**Closed by mikepenz** 2016-01-15 15:38 UTC
