### ISSUE TITLE
No selected items is not possible with AccountHeader

### ISSUE THREAD

**Issue by ianholing** [mikepenz/MaterialDrawer#383] opened 2015-06-02 11:40 UTC
I made my AccountHeader with one ProfileDrawerItem and one ProfileSettingDrawerItem. Then I attach it to my Drawer (with ".withSelectedItem(-1)") which have only 2 PrimaryDrawerItem, both with ".withCheckable(false)".

The App runs great at first (Nothing selected), but when you open and close again the AccountHeader, the first element on Drawer get selected.

I made a little workaround to avoid it adding to the first item this:

    .withSelectedColor(android.R.color.transparent)
    .withSelectedTextColor(R.color.material_drawer_primary_text)
    .withSelectedIconColor(R.color.material_drawer_primary_icon)

**Comment by mikepenz** [comment] 2015-06-02 21:27
@ianholing thanks. I have seen the short video @alorma sent to me according this issue and i will fix this issue.

**Comment by ianholing** [comment] 2015-06-03 11:29
Great thank YOU. Keep up this great work

**Comment by mikepenz** [comment] 2015-06-03 20:04
@ianholing just tested this with the `.withSelectedItem(-1)` and opening and closing the Accountslist, and i can't reproduce your issue. Do you do anything else inside your onProfileChanged listener?

I also tried it with setting the selection via the `result.setSelection(-1)` method. This one has a small issue that it does not allow `position == -1`. i changed this, so a removing the selection is possible. will be in the next version.

**Comment by ianholing** [comment] 2015-06-07 10:32
Hi Mike,
I use a delegate class to build the drawer, so I sent you the exact function by mail.

Hope it helps.
Thanks a lot!

**Comment by mikepenz** [comment] 2015-06-10 20:04
@ianholing just tried the code from your e-mail but i can't reproduce it. strange. :/ i removed all identifiers so perhaps this is the problem?

**Closed by mikepenz** 2015-06-10 20:04 UTC
Labels: bug, question
