### ISSUE TITLE
Integrate library in the Fullscreen example from Android Studio

### ISSUE THREAD

**Issue by adrcotfas** [mikepenz/MaterialDrawer#2225] opened 2018-02-18 16:42 UTC
## About this issue

Hi, awesome library but I can't seem to make it work as expected with the fullscreen example from Android Studio samples.
When the toolbar and status bar are hidden, everything is fine except this colored "placeholder" for the status bar.
Do you have any ideas?

![capture](https://user-images.githubusercontent.com/11249107/36354332-3eb8ff70-14db-11e8-87bf-e1f15b50a732.PNG)

When I remove the Drawer from my Activity, the colored "placeholder" is animated and disappears along with the status bar contents.

## Details
- [latest] Used library version
- [latest] Used support library version
- [latest] Used gradle build tools version
- [latest] Used tooling / Android Studio version
- [none] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment] 2018-02-18 19:10
Check out the sample's fullscreen example:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_fullscreen_dark_toolbar.xml


The problem is that the `DrawerLayout` would automatically make place for the statusbar via the `fitsSystemWindows` flag

**Comment by adrcotfas** [comment] 2018-02-19 17:20
FullscreenDraawerActivity is not implementing the "immersive mode" (auto hiding of the status bar and toolbar). I tried to add it but that colored line as seen in the screenshot above remains.

**Comment by mikepenz** [comment] 2018-03-19 15:48
@adrcotfas that has to do with the `fitsSystemWindows` flag and the insets handling of the `DrawerLayout`

**Comment by mikepenz** [comment] 2018-04-01 19:55
Please report back. closing in the meantime

**Closed by mikepenz** 2018-04-01 19:55 UTC
Labels: question
