### ISSUE TITLE
AccountHeader - update list while it is showing

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#847] opened 2015-12-01 08:14 UTC
I'm trying to add/remove profiles while the profiles list is showing... The problem is, that the list is not updating... To get the thing working I have to show/hide the selection list... Following functions are working for me:

```java
    private void deleteProfile(IProfile profile, boolean current)
    {
        // ... preperation...
		
        mAccountHeader.removeProfile(profile);

        // Hack to force header list to update...
        mAccountHeader.toggleSelectionList(this);
        mAccountHeader.toggleSelectionList(this);

        // update if necessary...
        if (current)
            mAccountHeader.setActiveProfile(mLocalProfile, true);
    }
	
    private void addProfile(DataSource dataSoruce)
    {
        IProfile newProfile = createProfileDrawerItem(dataSource);
        mAccountHeader.addProfile(newProfile, DataManager.getIndex(dataSource));
		
        mAccountHeader.setActiveProfile(newProfile, false);
	// here I call the profile clicked function =>
	// first boolean indicates if current profile is selected
	// second boolean indi to not close the drawers, as I would do it normally when clicking a profile
        handleProfileChanged(newProfile, false, false);
		
	// to reshow selection list, otherwise it's closed...
        mAccountHeader.toggleSelectionList(this);
    }
```

**Comment by MFlisar** [comment] 2015-12-01 09:43
I found an additional problem with that:

`mDrawer.getCurrentSelection()` mixes profiles and drawer items (depending on what is currently shown)... Probably by design, but somehow this was really unexpected for me... 

Currently, I have to do following to add a profile dynamically:

* show selection list
* add profile by clicking an entry in it
* selection list will hide automatically and I'll show a dialog
* ... I do whatever is necessary to add a profile...
* call handleProfileChanged which will check `mDrawer.getCurrentSelection()`
*  `mAccountHeader.toggleSelectionList(this);` AFTERWARDS (otherwise `mDrawer.getCurrentSelection()` in the previous point won't work as expected) to reshow the selection list

**Comment by mikepenz** [comment] 2015-12-01 10:25
@MFlisar as you already expected this is by design. 

If you switch to the account list, the whole drawer content is replaced with the profiles, so the new drawer content are the profiles temporary, so you also get the profile specific information. 

what do you try to do? 

regarding the changing of the profile list during the list is shown i will check how i can improve that.

**Comment by MFlisar** [comment] 2015-12-01 10:44
I show a drawer with accounts in it and an "add account" button at the bottom. I want to allow to remove accounts by long pressing an account and to add accounts by pressing the add button. I don't want the drawer to change while adding/removing accounts as it looks better. When adding an account I select it automatically and update the view behind the opened drawer and load the new accounts data, this update will check the current selection of the drawer which only works if the drawer does not show the selection list. Could be solved by remembering the current selection outside of the drawer though but that seems doing one thing twice.

I have a working solution now, but the above mentioned problems have to be handled manually...

Btw, you offer a `mAccountHeader.getActiveProfile()` getter, so this let's me assume `mDrawer.getCurrentSelection()` should not change when showing headers.. Still, I understand the problem, maybe it's possible to add a `getActiveDrawerItem()` or similar to the drawer, that would solve the `mDrawer.getCurrentSelection()` problem...

**Comment by mikepenz** [comment] 2015-12-01 19:32
@MFlisar ok will be improved / fixed in the next version. Here's a code snippet which will remove / add items and directly update the list

```java
//do not go back to the normal list after clicking a profile list item
.withResetDrawerOnProfileListClick(false)
.withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                        if (//add profile) {
                            //create the new profile
                            headerResult.addProfiles(newProfile);
                        } else if (//remove items) {
                            headerResult.removeProfileByIdentifier(103);
                        }

                        //false if you have not consumed the event and it should close the drawer
                        return true;
                    }
                })
```

**Closed** 2015-12-01 19:53 UTC
Labels: enhancement
