### ISSUE TITLE
problem with badge

### ISSUE THREAD

**Issue by dominicsavb** [mikepenz/MaterialDrawer#730] opened 2015-10-09 07:01 UTC
in my case:
I have 10 menu
I change badge at 5th menu with nav.updateBadge(5, "Update)
When I change nav.setSelection(1), that 5th menu Badge wont change....

but...
When I change badge at 6th, 7th, 8th, 9th, 10th menu... my 5th menu badge will change...

What's wrong with my menu...

Thank you

**Comment by mikepenz** [comment] 2015-10-09 07:08
@dominicsavb this method changes the badge with the identifier `5` not the badge at position `5`. You have to define identifiers for your `drawerItems` and then you can use those methods.

**Comment by mikepenz** [comment] 2015-10-09 07:10
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L114

```java
new PrimaryDrawerItem().withName(R.string.drawer_item_compact_header).withDescription(R.string.drawer_item_compact_header_desc).withIcon(GoogleMaterial.Icon.gmd_wb_sunny).withIdentifier(1).withSelectable(false),
```

See: `.withIdentifier(1)`

**Comment by dominicsavb** [comment] 2015-10-09 07:10
PrimaryDrawerItem already with identifier....

**Comment by mikepenz** [comment] 2015-10-09 07:12
@dominicsavb all your items have an identifier? which is **unique**?

**Comment by dominicsavb** [comment] 2015-10-09 07:13
My code.... the problem is at Galeri Quote.... 


when I start application with nav.setSelection(1) and nav.updateBadge(11,"Update).. it wont change...

but when I start application with nav.setSelection(14) and nav.updateBadge(11,"Update).. it change...

.addDrawerItems(
                        new PrimaryDrawerItem().withName("Alkitab").withIcon(R.drawable.icon_alkitab).withIdentifier(1).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Kalender Liturgi").withIcon(R.drawable.icon_kalenderliturgi).withIdentifier(2).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Kumpulan Doa").withIcon(R.drawable.icon_doa).withIdentifier(3).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Renungan Harian").withIcon(R.drawable.icon_bahasakasih).withIdentifier(4).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Daily Fresh Juice").withIcon(R.drawable.icon_dfj).withIdentifier(5).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Riwayat Orang Kudus").withIcon(R.drawable.icon_orangkudus).withIdentifier(6).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Jadwal Misa").withIcon(R.drawable.icon_jadwalmisa).withIdentifier(7).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Ibadat Harian").withIcon(R.drawable.icon_ibadatharian).withIdentifier(8).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Doa Rosario 1.0").withIcon(R.drawable.icon_doa_rosario).withIdentifier(9).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Inspirasi Hidup").withIcon(R.drawable.icon_inspirasihidup).withIdentifier(10).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Galeri Quote").withIcon(R.drawable.icon_galeriquote).withIdentifier(11).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Iklan Rohani").withIcon(R.drawable.icon_iklan).withIdentifier(12).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Pengumuman").withIcon(R.drawable.icon_pengumuman).withIdentifier(13).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Profile Developer").withIcon(R.drawable.icon_profil).withIdentifier(14).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new PrimaryDrawerItem().withName("Persembahan Kasih").withIcon(R.drawable.icon_donasi).withIdentifier(15).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.material_brown)),
                        new SectionDrawerItem().withName("Pengaturan"),
                        new ToggleDrawerItem().withName("Layar Selalu Nyala").withIcon(Octicons.Icon.oct_light_bulb).withChecked((userDb.getInt("LayarSelaluNyala", 0) == 0) ? false : true).withOnCheckedChangeListener(onCheckedChangeListener).withIdentifier(100),
                        new ToggleDrawerItem().withName("Notifikasi dari Server").withIcon(R.drawable.icon_notifikasi).withChecked((userDb.getInt("OpsiNotifikasi", 1) == 0) ? false : true).withOnCheckedChangeListener(onCheckedChangeListener).withIdentifier(101),
                        new ToggleDrawerItem().withName("Alarm Doa Angelus").withIcon(Octicons.Icon.oct_clock).withChecked((userDb.getInt("AlarmDoaAngelus", 0) == 0) ? false : true).withOnCheckedChangeListener(onCheckedChangeListener).withIdentifier(102),
                        new ToggleDrawerItem().withName("Alarm Doa Kerahiman Ilahi").withIcon(Octicons.Icon.oct_clock).withChecked((userDb.getInt("AlarmDoaKerahimanIlahi", 0) == 0) ? false : true).withOnCheckedChangeListener(onCheckedChangeListener).withIdentifier(103),
                        new PrimaryDrawerItem().withName("Pengaturan Lainnya").withIcon(R.drawable.icon_setting).withIdentifier(16)
                )

**Comment by mikepenz** [comment] 2015-10-09 07:20
@dominicsavb you use the latest version of the drawer?

(just a small hint: define the badgeStyle in a variable so you can reuse it and set it, as those all look the same :D)

**Comment by dominicsavb** [comment] 2015-10-09 07:41
Yap... today I upgrade to latest version...

Thank you for badgeStyle...

**Comment by dominicsavb** [comment] 2015-10-09 07:42
in my case... error is only at Galery Quote Menu....

**Comment by mikepenz** [comment] 2015-10-09 10:18
and you do not have any other logic somewhere?

**Comment by mikepenz** [comment] 2015-10-09 15:18
@dominicsavb just tried it and it works :D
http://codeshare.io/acBLQ

**Comment by dominicsavb** [comment] 2015-10-10 01:51
the result is like this...

![tempfileforshare](https://cloud.githubusercontent.com/assets/6405946/10408576/bf9378bc-6f2b-11e5-9487-2f743c1cb6fa.jpg)

badge style is same like other menu... at Galeri Quote, there is a badge with no text... after I scroll up and scroll down the menu, the text is appearing.... so whats wrong with this??

Thank you

**Comment by mikepenz** [comment] 2015-10-10 04:07
I really can't reproduce it. With the code i sent you earlier with the badge set for the one item it does not happen. 

It would be great if you could provide a small sample app demoing this issue. So i can debug and look into it?

**Comment by dominicsavb** [comment] 2015-10-12 05:02
for caching just use this code RecyclerViewCacheUtil.getInstance().withCacheSize(2).init(result); ??

**Comment by mikepenz** [comment] 2015-10-12 06:35
What do you mean with your comment? 

the line of code you shared will pre create 2 drawerItem views per type, to improve the first scroll performance if you have a list with many different types

**Comment by mikepenz** [comment] 2015-10-14 18:37
I will close this for now. Please get in touch again with more details. And probably a demo app which showcases your above issue so i can debug and fix it

**Closed by mikepenz** 2015-10-14 18:37 UTC
Labels: question
