### ISSUE TITLE
material_drawer_primary_dark doesn't work?

### ISSUE THREAD

**Issue by tral** [mikepenz/MaterialDrawer#20] opened 2015-02-17 07:10 UTC
Hi, in your sample I'm trying to override colors (in colors.xml of the App).

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Material SAMPLE DARK colors -->

    <color name="material_drawer_primary">#4BAE4F</color>
    <color name="material_drawer_primary_dark">#FF4081</color>
    <color name="material_drawer_primary_light">#C8E5C9</color>
    <color name="material_drawer_accent">#FE5621</color>

    <color name="material_drawer_background">#303030</color>
    <color name="material_drawer_icons">#000</color>
    <color name="material_drawer_primary_text">#FFF</color>
    <color name="material_drawer_secondary_text">#DEDEDE</color>
    <color name="material_drawer_hint_text">#ABABAB</color>
    <color name="material_drawer_contrast_text">#000</color>
    <color name="material_drawer_divider">#555555</color>
    <color name="material_drawer_selected">#262626</color>

</resources>
```

Status bar has to be PINK according to this settings, but it's still dark green. Android 5.0.1, Nexus 5.

![Image of error](http://i.imgur.com/oo8TpCD.png)

**Comment by mikepenz** [comment] 2015-02-17 20:41
Oh sorry. that's an issue of the description. to get the colors working you also have to use the theme. 

As an alternative you can also set the following values. (note the materialDrawer is used normally with an AppCompat theme)

```xml
        <item name="colorPrimary">@color/material_drawer_primary</item>
        <item name="colorPrimaryDark">@color/material_drawer_primary_dark</item>
        <item name="colorAccent">@color/material_drawer_accent</item>

        <item name="android:windowBackground">@color/material_drawer_background</item>
```

**Comment by tral** [comment] 2015-02-18 05:01
Hi, on API 21 it ignores colorPrimaryDark if you include this 2 lines, so If you include this lines and override items in your app's "\vaues-v21\styles.xml":
```
<item name="android:windowDrawsSystemBarBackgrounds">true</item>
<item name="android:windowTranslucentStatus">true</item>
```
It looks like (colorPrimaryDark is #FF4081 - pink):
![Imgur](http://i.imgur.com/nUvWGj1.png)

If you don't include this lines and override items in your app's \vaues-v21\styles.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="AppTheme1" parent="Theme.AppCompat.NoActionBar">

        <!---
          <item name="android:windowDrawsSystemBarBackgrounds">true</item>
          <item name="android:statusBarColor">@android:color/transparent</item>
          <item name="android:windowTranslucentStatus">true</item>
        -->
        <item name="colorPrimary">#c6ff00</item>
        <item name="colorPrimaryDark">#FF4081</item>
        <item name="colorAccent">#76ff03</item>

    </style>
</resources>

```
you'll get something like this:
![Imgur](http://i.imgur.com/ob46Enq.png)

**Comment by mikepenz** [comment] 2015-02-18 06:55
@tral i really give you the advise to use the MaterialDrawerTheme provided within the library to help you with the theme stuff. Just check out the sample app how it's done. 

The thing is the issues you face right now are not caused by the MaterialDrawer lib, it's just general Android design stuff :D

Have you checked the sample app? Or do you need any infos regarding definitions or stuff set within the sample app?

**Comment by mikepenz** [comment] 2015-02-18 06:56
@tral i'll close this issue, because it's not caused by the MaterialDrawer. 
you can still write here, and i'll try to help you with the design. 

Cheers.

**Closed by mikepenz** 2015-02-18 06:56 UTC
Labels: enhancement

**Comment by tral** [comment] 2015-02-18 07:33
ok, I use theme from the lib now.
How to make ActionBar green and Status bar pink for example?
I cannot achieve this, I always get Status Bar filled in a darker color of Action Bar.

**Comment by mikepenz** [comment] 2015-02-18 07:52
If you use the theme provided by the lib, just overwrite the colors within the colors.xml as shown in the README.md

**Comment by tral** [comment] 2015-02-18 10:50
yep, I tried, but
changing of material_drawer_primary_dark doesn't make any sense on Android 5 , maybe, because of transparent toolbar? Is there any workaround for that?

**Comment by mikepenz** [comment] 2015-02-18 20:27
Workaround for what? the transparent toolbar? If you don't like it use your own style.
but then it has to set the primary, accent, ... colors. 

the material_drawer colors and so on are used for elements within the library itself. so it makes sense.
