### ISSUE TITLE
Wrong coloring again

### ISSUE THREAD

**Issue by rubengees** [mikepenz/MaterialDrawer#1180] opened 2016-04-13 18:23 UTC
So I just stumbled across another coloring issue.
This happens in conjunction with programmatically setting the selection:
```java
drawer.setSelection(id);  //id points to an existing DrawerItem
```

There are 2 cases:

I currently view a normal section and select another:
The new one becomes colored but lacks the gray background.

A <- Now selected: No background
B <- Previously selected: Correctly colored
-- Sticky section --
C
D

I currently view a sticky footer section and select a normal one:
The new becomes colored correctly but the coloring of the sticky one is not cleared.

A <- Now selected: Correctly colored
B
-- Sticky section --
C
D <- Previously selected: Not cleared

My items look like this:

```java
new PrimaryDrawerItem().withName(R.string.drawer_item_news)
                .withIcon(CommunityMaterial.Icon.cmd_newspaper)
                .withSelectedTextColorRes(R.color.primary)
                .withSelectedIconColorRes(R.color.primary)
                .withBadgeStyle(new BadgeStyle()
                        .withColorRes(R.color.primary)
                        .withTextColorRes(android.R.color.white))
                .withIdentifier(DRAWER_ID_NEWS)
```

I tested that on my OnePlus 2 with 6.0.1 and an N preview emulator.
I think this happens since the changes with FastAdapter. Currently using the latest Version.

I hope this is somewhat understandable. If not, feel free to ask anything.

**Comment by mikepenz** [comment] 2016-04-15 13:52
@rubengees for the first you should be able to improve it by defining
```java
result.getAdapter().withSelectWithItemUpdate(true)
```
this will trigger an `notifyItemChanged` upon select. Normaly I will just `setActiviated()` and trust on the Android API to forward this state to the view. Seems like this does not happen in your case. 

The later might be related to something else, as the  `StickyFooter` falls out from the `FastAdapter` and is just a normal `LinearLayout`

**Comment by rubengees** [comment] 2016-04-15 14:23
Sadly doesn't help...

**Comment by mikepenz** [comment] 2016-04-15 14:56
@rubengees I also can't reproduce the first one on my `Nexus 6P` with Android 6.0.1. 
Where do you set the selection? And what happened before?

**Comment by rubengees** [comment] 2016-04-15 15:23
Let's say I have the sections A, B and C. In my App if the user presses the back button and is not currently viewing section A I want to show section A before closing the App.

To do so I have a method `handleBackPressed`, which looks like so:

```java
public boolean handleBackPressed() {
        if (isDrawerOpen()) {
            drawer.closeDrawer();

            return true;
        } else if (currentDrawerItemId != ID_A) {
            select(ID_B);

            return true;
        } else {
            return false;
        }
    }
```

`select` is as simple as

```java
public void select(@DrawerItemId int id) {
    drawer.setSelection(id);
}
```

I think this happens because the framework is handling something incorrect like you mentioned in the other issue with coloring.

**Comment by mikepenz** [comment] 2016-04-20 19:14
@rubengees sorry I am overdue with the second issue. I do not forget about it :D

**Comment by mikepenz** [comment] 2016-04-20 19:47
@rubengees your first issue I can't reproduce. :/

**Comment by rubengees** [comment] 2016-04-20 19:55
No problem, take your time!
I will try to create a sample App zu reproduce the bug/framework issue tomorrow.

**Comment by rubengees** [comment] 2016-04-24 21:37
The second issue is solved with the new version.
I tried to build a sample App which reproduces the error, but it worked just fine...
I have no idea why but it still happens in the real App. I have to live with it I guess.. :D

**Comment by mikepenz** [comment] 2016-04-25 06:08
Hmmm you have overwritten a color or something like this? 

Will close this now. You can reopen if you find out why this might be an issue in your app

**Closed by mikepenz** 2016-04-25 06:08 UTC
Labels: bug, question
