### ISSUE TITLE
semi-transparent color over view under DrawerLayout

### ISSUE THREAD

**Issue by tjmille2** [mikepenz/MaterialDrawer#2186] opened 2018-01-25 01:36 UTC
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code
It doesn't happen all the time, but it happens often enough to warrant an investigation.
![device-2018-01-24-200938](https://user-images.githubusercontent.com/19319335/35366192-30839d0a-0146-11e8-8241-8997416ec142.png)

When I add the drawer to my layout, I sometimes get the colorPrimary of the activity, in a semi-transparent overlay over the main view under the DrawerLayout.

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment] 2018-01-26 11:24
@tjmille2 it really seems to be related to your application. The MaterialDrawer itself does not define any color like this. 

Also the `DrawerLayout` (by Google)  scrim is black and not the accent color. :/ 

Do you have such a color somewhere in your app? 

Is it reproducible in the sample?

**Comment by mikepenz** [comment] 2018-02-04 13:09
Closing this now. Please provide further information like a sample app which allows a investigation

**Closed by mikepenz** 2018-02-04 13:09 UTC
Labels: question
