### ISSUE TITLE
Empty Space generated in Lollipop version

### ISSUE THREAD

**Issue by CeJienAJPC** [mikepenz/MaterialDrawer#1070] opened 2016-03-06 12:22 UTC
Below the StickyDrawerItems, empty space is getting created on devices with lollipop. However, this is not the case with pre lollipop devices
Any idea?

Regards
![lollipop](https://cloud.githubusercontent.com/assets/15603039/13554051/b21bee3c-e3c3-11e5-8a22-bf8335a4c694.png)
![pre lollipop](https://cloud.githubusercontent.com/assets/15603039/13554053/c107b0a2-e3c3-11e5-89a6-b1f25c70b6ae.png)

**Comment by mikepenz** [comment] 2016-03-06 13:58
@CeJienAJPC just tried the `StickyDrawerItems` via the `AdvancedActivity` of the sample in emulators from APi 17 up to 22, but was not able to reproduce this empty space you have. 
Do you get this empty space inside the sample app too? If yes, on which device did you test it?

Which theme are you using? How did you configure the drawer?

**Comment by mikepenz** [comment] 2016-03-09 13:52
@CeJienAJPC please report back. I will close this until additional details are provided, as I can't reproduce this on any of my emulators / devices

**Closed by mikepenz** 2016-03-09 13:52 UTC
Labels: question
