### ISSUE TITLE
android.content.res.Resources$NotFoundException on devices with < Android API level 26

### ISSUE THREAD

**Issue by AndroVid** [mikepenz/MaterialDrawer#2489] opened 2019-08-30 09:15 UTC
We are gettting many Resources$NotFoundException exceptions from devices with  **Android API level < 26.**  I checked that the same issue was reported before but closed without fixing.

Our **min SDK is 21**. So we get errors from devices with Android API version 21 to 25.
We could not reproduce the issue on our test devices.

We have been using this library for years, recently we migrated to androidx. I wonder if it is related to that.

## Details
- [ **6.1.2** ] Used library version
- [X ] Used support library version
AndroidX is used
implementation '**androidx.appcompat:appcompat:1.0.2**'
    implementation '**androidx.gridlayout:gridlayout:1.0.0**'
    implementation '**androidx.cardview:cardview:1.0.0**'
    implementation '**androidx.recyclerview:recyclerview:1.0.0**'
    implementation '**com.google.android.material:material:1.1.0-alpha07**'
- [ ] Used gradle build tools version
classpath '**com.android.tools.build:gradle:3.4.1**'
        classpath '**com.google.gms:google-services:4.2.0**'
        classpath '**com.google.firebase:firebase-plugins:1.2.0**'
- [3.4.1] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ X] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ X] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md
<img width="670" alt="Screen Shot 2019-08-30 at 12 02 20 PM" src="https://user-images.githubusercontent.com/32763974/64008933-a722a100-cb1f-11e9-827f-88da1bb794ed.png">
<img width="958" alt="Screen Shot 2019-08-30 at 12 02 08 PM" src="https://user-images.githubusercontent.com/32763974/64008936-a7bb3780-cb1f-11e9-9e1b-ac3b2d986f95.png">

)

**Comment by mikepenz** [comment] 2019-08-30 09:21
SDK 7 is not supported. 

Only minSDK 14 is supported: https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L13

**Comment by AndroVid** [comment] 2019-08-30 09:26
Hi Mike, I didn't mean SDK version 7, I meant Android Nougat.

Min SDK version is currently 21 in our app.

**Comment by mikepenz** [comment] 2019-08-30 09:37
hmmm do you use the default items or do you have any modifications? 
Do you use perhaps some drawable which has some theme color attributes or something which might could cause problems?

**Comment by AndroVid** [comment] 2019-08-30 09:58
Here is the code to setup the Drawer. All drawables exist in the project as PNG or vector format. 

```
public static Drawer setupNavigationDrawer(final Activity activity, Toolbar toolbar, int selectedItem)
    {
        //if you want to update the items at a later time it is recommended to keep it in a variable
        PrimaryDrawerItem drawerEmptyItem= new PrimaryDrawerItem().withIdentifier(0).withName("");
        drawerEmptyItem.withEnabled(false);


        PrimaryDrawerItem drawerHome = new PrimaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_HOME )
                .withName(R.string.HOME ).withIcon(R.drawable.ic_home_white_36dp);
        PrimaryDrawerItem drawerItemVideoList = new PrimaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_VIDEO_LIST )
                .withName(R.string.VIDEOS ).withIcon(R.drawable.ic_video_library_large);
        PrimaryDrawerItem drawerItemManageImageList = new PrimaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_IMAGE_LIST )
                .withName(R.string.PHOTOS ).withIcon(R.drawable.ic_photo_library_large);

        PrimaryDrawerItem drawerItemRecycleBin = new PrimaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_RECYCLE_BIN )
                .withName(R.string.RECYCLE_BIN ).withIcon(R.drawable.ic_delete_sweep_white_36dp );

        SecondaryDrawerItem drawerItemOptions = new SecondaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_OPTIONS )
                .withName(R.string.SETTINGS).withIcon(R.drawable.ic_settings).withSelectable( false );
        SecondaryDrawerItem drawerItemHelp = new SecondaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_HELP )
                .withName(R.string.HELP ).withIcon(R.drawable.ic_help_outline).withSelectable( false );
        SecondaryDrawerItem drawerItemFeedback = new SecondaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_FEEDBACK )
                .withName(R.string.FEEDBACK ).withIcon(R.drawable.ic_feedback).withSelectable( false );
        //SecondaryDrawerItem drawerItemTranslate = new SecondaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_TRANSLATE )
        //        .withName(R.string.LOCALIZATION ).withIcon(R.drawable.ic_translate ).withSelectable( false );

        SecondaryDrawerItem drawerItemTwitter = new SecondaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_TWITTER )
                .withName(R.string.FOLLOW_US_ON_TWITTER ).withIcon(R.drawable.ic_twitter).withSelectable( false );
        SecondaryDrawerItem drawerItemFacebook = new SecondaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_FACEBOOK )
                .withName(R.string.LIKE_US_ON_FACEBOOK ).withIcon(R.drawable.ic_facebook).withSelectable( false );

        //create the drawer and remember the `Drawer` result object
        DrawerBuilder drawerBuilder = new DrawerBuilder()
                .withActivity(activity)
                .withToolbar(toolbar)
                .withHeader( getHeaderView( activity ) )
                .withCloseOnClick(true)
                .withSelectedItem( selectedItem )
                .addDrawerItems(
                        drawerHome,
                        drawerItemVideoList,
                        drawerItemManageImageList,
                        drawerItemRecycleBin,
                        new DividerDrawerItem(),
                        drawerItemOptions,
                        drawerItemHelp,
                        drawerItemFeedback,
                        //drawerItemTranslate,
                        drawerItemTwitter,
                        drawerItemFacebook
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        processOnItemClick( activity, (int)drawerItem.getIdentifier(), true );
                        return false;
                    }
                });

        if ( !Version.IS_PRO() )
        {
            SecondaryDrawerItem drawerItemBuyPro = new SecondaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_BUY_PRO )
                    .withName(R.string.buy_androvid_pro_title).withIcon(R.drawable.ic_shop).withSelectable( false );
            List<IDrawerItem> stickyItems = new ArrayList<>();
            stickyItems.add( drawerItemBuyPro );
            drawerBuilder = drawerBuilder.withStickyDrawerItems(stickyItems);
        }
        return drawerBuilder.build();
    }
```

**Comment by mikepenz** [comment] 2019-08-30 10:10
Oh you still use v6.1.2



But yes the problem is definitely one of the icons you provide: https://github.com/mikepenz/MaterialDrawer/blob/v6.1.2/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDescribeableDrawerItem.java#L98

We already use the AppCompatResources class which should support as much as possible: https://github.com/mikepenz/MaterialDrawer/blob/v6.1.2/library/src/main/java/com/mikepenz/materialdrawer/holder/ImageHolder.java#L103

But yeah there is nothing which I can do from library side. Seems those phones do not support some feature you use in one of your icons

**Comment by AndroVid** [comment] 2019-08-30 10:27
Those icons are either usual PNG format or Vector format, and we don't do anything special.

Is there any workaround that we can do in our app code to prevent the exception?

We didn't upgraded your library since we are not sure about the stability of v7.0.0 (they are all tagged as pre-release)
Do you suggest upgrading to v7.0.0?

**Comment by mikepenz** [comment] 2019-08-30 10:34
@AndroVid 

the icons in the vector format, do you by any chance specify colors via theme attributes, or colorStateList or something more advanced which might be not backported via the support libraries. According to the stacktrace one of the resources you provide is simply not found or could not be resolved by the system. 

Related v7 release. 
The main reason it is marked as pre-release is that it depends on the material components alpha07 or newer: https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L22
And that we potentially still wait for having a DSL included. 
In general it is not necessary though. :D

**Comment by AndroVid** [comment] 2019-08-30 11:17
I checked that we were getting the error in the past as well, so I don't think it's because of Vector drawables because we've added them recently.

What about DividerDrawerItem ? there are Theme related codes there.

**Comment by mikepenz** [comment] 2019-08-30 11:27
According to the stacktrace it is not related to that itme. it is in the `AbstractBadgeableDrawerItem` which is used from the PrimaryDrawerItem for example

And the code which crashes resolves the icon resource you specified

**Comment by AndroVid** [comment] 2019-08-30 15:14
Hi Mike, we have to find a workaround solution to this. Currently this is the top exception in Fabric, and it seems num of exps increased with our latest release which is currently staged roll-out.

I propose two workarounds ( they are not good but we couldn't find the root cause, we have to make an urgent fix)

1. Check out the library code v6.1.2 and enclose the exception code in ImageHolder, leave icon as null.

2. Inside our app code, call AppCompatResources.getDrawable in a try-catch block, if it fails don't use icon for that drawer item. (Also later on we can analyze which drawable causes the problem)

what do you think?

**Comment by mikepenz** [comment] 2019-08-30 15:32
I would suggest doing the second approach. e.g you can more easily without big changes see if resolving the icon works and can send a crashltyics event in the case of failure. 

But it is definitely weird. as the stacktrace directly leads to the AppCompatResources and that one loads the ressources which got defined. 

Could it be that you try to load one icon via a `attr` instead of a `drawable`?

**Comment by AndroVid** [comment] 2019-08-30 15:44
No, we use our own icons under /drawable directories.

I checked all drawables again. Most of them are in Vector format, and they exist in 2 places /drawable and /drawable-sw600dp in order to support high resolution devices better. However couple of icons are PNG images exist in /drawable-hdpi, /drawable-xhdpi etc..

Main change in our release we started uploading bundle instead of APK. I wonder if sth goes wrong in Google Play's apk generation process.

I tried the 2nd weird workaround approach by giving non-existent drawable id and get the same exception.

**Comment by mikepenz** [comment] 2019-08-30 15:48
Oh this sounds actually like a very interesting thought. 

Could theoretically be, that the app bundling thinks a specific resources will not be necessary for a device, eliminates it, and then it would be needed after all

**Comment by mikepenz** [comment] 2019-09-01 11:34
In case you find out additional details, I would be super curious about the problem. 

I am still almost sure it is not directly related to this library (according to the stack trace and the issue description) 

We may close this issue though unless we can identify it being an actual issue of the library.

**Comment by AndroVid** [comment] 2019-09-01 21:41
Update on the issue:

Applied the following workaround for each Drawer item:

```
        Drawable icon = null;
        try
        {
            icon = AppCompatResources.getDrawable(activity, R.drawable.ic_home_white_36dp);
        }catch ( Throwable e )
        {
            Log.e("NavigationDrawerUtil.setupNavigationDrawer, cannot load ic_home_white_36dp!");
            CrashlyticsWrapper.logException( e );
        }
        PrimaryDrawerItem drawerHome = new PrimaryDrawerItem().withIdentifier( DRAWER_MENU_ITEM_HOME )
                .withName(R.string.HOME );
        if ( icon != null )
        {
            drawerHome = drawerHome.withIcon( icon );
        }
```
Uploaded BUNDLE format and from Fabric logs we are getting exceptions from PNG images but not from Vector XMLs.

We had another issue regarding Bundle usage ( about native libraries) So we uploaded in APK format, and so far no exceptions. I will write any other updates about the issue.

**Comment by mikepenz** [comment] 2019-09-02 06:47
Thanks for the update. 

That's super interesting and super weird. 

I would have hoped / expected that the bundle feature is more secure already.

**Closed by mikepenz** 2019-09-02 06:47 UTC
Labels: question
