### ISSUE TITLE
Slow work on the Nexus 5x with Android 8.1.

### ISSUE THREAD

**Issue by EfremovAV** [mikepenz/MaterialDrawer#2240] opened 2018-02-28 12:15 UTC
## About this issue

When testing an application on Nexus 5x with Android 8.1. there was a significant slowdown in work the MaterialDrawer. On other devices, with older versions of OS, a similar problem is not noticed. 

What could be the cause of the problem and how to fix it?

## Details
 compile('com.mikepenz:materialdrawer:6.0.6@aar') {
        transitive = true
    }
    compile 'com.mikepenz:iconics-core:3.0.3@aar'
    compile 'com.mikepenz:iconics-views:3.0.3@aar'
    compile 'com.mikepenz:fontawesome-typeface:4.7.0.2@aar'

 compileSdkVersion 27
    buildToolsVersion "27.0.2"

## Checklist

- [ X] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by grote** [comment] 2018-03-01 20:30
Could be a duplicate of #2238

**Comment by mikepenz** [comment] 2018-03-09 16:58
@EfremovAV can you please elaborate more? Is this related to the linked issue?

**Comment by EfremovAV** [comment] 2018-03-09 17:35
It's difficult for me to say whether this is related to the linked issue, because I didn't do same analysis. But I can say that there is a slowdown on the Nexus 5x with Android 8.1. On other devices, with an earlier version of Android there is no problem. Including on the OnePlus 5T with Android 8.0. 

So I don't know what the problem is in the Nexus 5x or in the Android 8.1 or together))

**Comment by mikepenz** [comment] 2018-03-19 15:31
Closing this one, as it is most likely a duplicate of #2238

**Closed by mikepenz** 2018-03-19 15:31 UTC
