### ISSUE TITLE
Resources$NotFoundException: drawable/material_drawer_shadow_top with resource ID #0x7f0700e3

### ISSUE THREAD

**Issue by ixiDev** [mikepenz/MaterialDrawer#2703] opened 2021-02-02 20:34 UTC
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ 8.3.1] Used library version 
- [ v4:1.0.0] Used support library version
- [4.1.2 ] Used gradle build tools version
- [ 4.1.2] Used tooling / Android Studio version
- Other used libraries, potential conflicting libraries
```groovy
  // MaterialDrawer
    api("com.mikepenz:materialdrawer:8.3.1")
    api("com.mikepenz:materialdrawer-nav:8.3.1")
    api("com.mikepenz:materialdrawer-iconics:8.3.1")
    //FontAwesome
    api("com.mikepenz:fontawesome-typeface:5.9.0.2-kotlin@aar")
```

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

##Log message
```

2021-02-02 20:37:46.161 18687-18687/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.*, PID: 18687
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.*/com.*.MobileMainActivity}: android.content.res.Resources$NotFoundException: Drawable com.*:drawable/material_drawer_shadow_top with resource ID #0x7f0700e3
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3310)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3459)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7564)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.content.res.Resources$NotFoundException: Drawable com.*:drawable/material_drawer_shadow_top with resource ID #0x7f0700e3
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/material_drawer_shadow_top.xml from drawable resource ID #0x7f0700e3
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:898)
        at android.content.res.ResourcesImpl.originalLoadDrawable(ResourcesImpl.java:679)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:586)
        at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:307)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:922)
        at android.content.res.Resources.getDrawable(Resources.java:861)
        at android.content.Context.getDrawable(Context.java:696)
        at android.view.View.setBackgroundResource(View.java:23364)
        at n.g.c.a.Y(:2)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.e(:1)
        at com.*.MobileMainActivity.onCreate(:18)
        at android.app.Activity.performCreate(Activity.java:7916)
        at android.app.Activity.performCreate(Activity.java:7903)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3285)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3459)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7564)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.view.InflateException: Class not found x
        at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:224)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:141)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1402)
        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1361)
        at android.content.res.ResourcesImpl.createFromXmlForDensity(ResourcesImpl.java:1615)
        at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:963)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:882)
2021-02-02 20:37:46.171 18687-18687/? E/AndroidRuntime: 	... 25 more
    Caused by: java.lang.ClassNotFoundException: Didn't find class "x" on path: DexPathList[[zip file "/data/app/com.*-r4UTZVrpnzsieDDytjcejA==/base.apk"],nativeLibraryDirectories=[/data/app/com.*-r4UTZVrpnzsieDDytjcejA==/lib/arm64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:205)
        	... 31 more
2021-02-02 20:38:28.659 1599-6531/? E/InputDispatcher: Window handle Window{b9015b5 u0 Application Error: com.*} has no registered input channel
2021-02-02 21:08:03.629 4013-4013/? E/Recents: packageMonitor   onPackageModified  packageName=com.*   mIsRecentsWithinLauncher=true
2021-02-02 21:08:12.742 4013-4013/? E/Recents: packageMonitor   onPackageModified  packageName=com.* mIsRecentsWithinLauncher=true
2021-02-02 21:08:13.200 15389-15525/? E/Launcher.AllAppsList: Can't load postion for packageName: com.*activityName: com.*.MobileMainActivity
```

## Solution
 exclude  material drawer drawable xml file from proguard by adding **res/rew/keep.xml** 

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/material_drawer_*"/>
```

I don't know if this right or not, because you mentioned in #2150  that MaterialDrawer library doesn't need proguard rules

Thanks again

**Comment by mikepenz** [comment] 2021-02-02 23:53
@ixiDev could you possibly add additional detail on your configuraiton. proguard itself would not remove ressources. 

The `keep.xml` is a different feature from the android system. but this has not been an issue for other users before. 

So I am curious about the setup which forces the build system to remove files.

**Comment by ixiDev** [comment] 2021-02-03 00:03
@mikepenz  I am really don't know why proguatd removed this xml files , here is my app config
 i have a 4 modules
-  app
-  tv 
- mobile
- common
when i  enable progurad for debug build and  running 
`./gradlew assembleDebug`
 and install the debug apk  and it's working finde but in release build not working
so i checked the release apk and progurad resources.txt and i found that progurad remove the content of **material_drawer_shadow_top.xml**
and that's crashing the app

**Comment by mikepenz** [comment] 2021-02-03 08:23
It's very interesting 🤔  there's no reason why it should think it can remove this resource :/ 
Especially as it is directly referenced in the source: https://github.com/mikepenz/MaterialDrawer/blob/11eea562700098a3e6a39eca15808fa94bd75c1c/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUtils.kt#L200

https://developer.android.com/studio/build/shrink-code#troubleshoot-resource-shrink

I assume you have shrinkResources activated in your release build process?

**Comment by ixiDev** [comment] 2021-02-03 19:17
Hi  @mikepenz 

i have **shrinkResources** enabled in app module ( release build )

here is config of all modules :

-app (main module)

```groovy
    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        getByName("debug") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }

```
- mobile 

> note that i can't use  `isShrinkResources=true` in tv and mobile modules when i use it i got this message : 
> **Resource shrinker cannot be used for libraries.**

```groovy
        getByName("release") {
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
```

- tv

```groovy
        getByName("release") {
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
```

i had enabled    **isMinifyEnabled**  **isShrinkResources**  for both release and debug build and the app work fine in debug but in release not.
i check the apk and poguard mapping files and i fond this : 
Proguard doesn't remove  **material_drawer_shadow_top.xml**  but it's just remove the content here is the file 


**material_drawer_shadow_top.xml**

```xml
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:angle="270"
        android:endColor="#40000000"
        android:startColor="@android:color/transparent" />
</shape>
```

after release build 

```xml
<?xml version="1.0" encoding="utf-8"?>
<x />
```

and here is snapshot from proguard **resources.txt**

```
Skipped unused resource res/drawable/material_drawer_rectangle_mask.xml: 372 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/material_drawer_shadow_bottom.xml: 456 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/material_drawer_shadow_top.xml: 456 bytes (replaced with small dummy file of size 104 bytes)
```

**proguard-rules.pro** for mobile module

```pro
-keepclassmembers class * implements androidx.viewbinding.ViewBinding {
     public static ** bind(android.view.View);
}

```

> and note that i use MaterialDrawer library only in mobile module with is dependencies

```groovy
   // MaterialDrawer
    api("com.mikepenz:materialdrawer:8.3.1")
    api("com.mikepenz:materialdrawer-nav:8.3.1")
    api("com.mikepenz:materialdrawer-iconics:8.3.1")
    //FontAwesome
    api("com.mikepenz:fontawesome-typeface:5.9.0.2-kotlin@aar")
```

I hope this details will help for something.  :crying_cat_face:

**Comment by mikepenz** [comment] 2021-02-03 19:50
Thank you very much @ixiDev for this detailed report. 

For the time being please keep on using 

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/material_drawer_*"/>
```

we'll investigate what we can do to improve this out of the box

**Comment by ixiDev** [comment] 2021-02-03 20:58
Thanks a lot @mikepenz  , i will keep using **keep.xml** if i found another solution i will let u know :heart:

**Comment by mikepenz** [comment] 2021-02-06 14:38
@ixiDev upon closer investigation. the problem is not due to the `MaterialDrawer` itself, or the shrinker. 

The issue only occurs if the `proguard-android-optimize.txt` rules are used. If you replace it with the normal `proguard-android.txt` it will work properly. 

This is because it seems the `-optimize` approach either breaks the reference check for the shrinker or enables the `strict` shrinkMode. You can read more on this over here: https://developer.android.com/studio/build/shrink-code#strict-reference-checks

---

Based on this information I'd currently not plan to force keeping the references as the shrinker usually correctly identifies those resources being referenced in code and being used. 

If you prefer to stay with `proguard-android-optimize.txt`, I'd suggest to retain the use of the `keep.xml` https://github.com/mikepenz/MaterialDrawer/issues/2703#issuecomment-772777532

Just be aware that there's a good chance of more things being required to manually marked as being kept. (not only in the MaterialDrawer library)

**Comment by ixiDev** [comment] 2021-02-06 21:07
@mikepenz I have tested now with `proguard-android.txt` and it's as you say , the problem comes from `proguard-android-optimize.txt` . but when i use `proguard-android.txt` i need to add rules manually for all my dependencies like **Hilt** library ( i got crash ,  `proguard-android.txt` remove  `@AndroidEntryPoint` interface ) 
anyway, i will keep using **keep.xml**   [#2703 (comment)](https://github.com/mikepenz/MaterialDrawer/issues/2703#issuecomment-772777532) 
Thanks a again , you can close this issue :smile:

**Closed** 2021-02-07 07:50 UTC
Labels: enhancement
