### ISSUE TITLE
.withDrawerWidthDp(64) not working on .buildView() .getSlider()

### ISSUE THREAD

**Issue by FabianTerhorst** [mikepenz/MaterialDrawer#207] opened 2015-04-11 10:54 UTC
Hello,

i have tried to change the drawer with on the EmbeddedDrawerActivity.class sample but the withDrawerWidthDp(64) method do nothing. Is this a bug, or is this not possible, because getSlider() returns a relative layout not the drawer layout?

**Comment by raghunandankavi2010** [comment] 2015-04-11 15:35
Yes it does not work with `buildView()`. You can change the width of the `FrameLayout` in your xml.

Or just use `build()` and set eh width of the drawer.

**Comment by FabianTerhorst** [comment] 2015-04-11 16:22
slider.setLayoutParams(new ViewGroup.LayoutParams(normalWidth,
                ViewGroup.LayoutParams.WRAP_CONTENT));
fixed the problem.

**Comment by raghunandankavi2010** [comment] 2015-04-11 16:34
@FabianTerhorst  That will also work. I you see the `code mSliderLayout.addView(mListView, params);` So i changed the width to `mDrawerWidth`.

But its not a bug its for the demo purpose. You won't be adding a drawer view to your framelayout.

**Comment by mikepenz** [comment] 2015-04-12 10:02
@FabianTerhorst if you use the buildView method you have to set the drawerWidth on your own because this value is only used for the drawer not the view.

**Closed by mikepenz** 2015-04-12 10:02 UTC
Labels: question
