### ISSUE TITLE
Pixelated materialdrawer icons

### ISSUE THREAD

**Issue by tobybonhof** [mikepenz/MaterialDrawer#2388] opened 2018-11-08 19:41 UTC
## About this issue

- Briefly describe the issue

The icons that im using generated with android studio at 24dp from materialdesignicons show up pixelated when calling .withIcon on drawer items. How come?

- How can the issue be reproduced / sample code

Download svg from material design icons. import into project new -> vector asset and set it on a drawer item by calling:

                PrimaryDrawerItem().withName("Settings").withIcon(R.drawable.ic_sidenav_settings).withTag("settings")

## Details
- [ ] Used library version
latest
- [ ] Used support library version
androidx

![screenshot_20181108-204005](https://user-images.githubusercontent.com/2817395/48223226-de5c7180-e396-11e8-8371-1b0c2ca5aabd.png)

**Comment by mikepenz** [comment] 2018-11-08 20:09
@tobybonhof display them in a ImageView somewhere and check how they look there? 

I assume something with the conversion caused issues?

**Comment by tobybonhof** [comment] 2018-11-08 20:11
What is the desired size.. Because i always use this feature and never caused me any trouble before. I generate the icons at 24dp. Is this to small?

**Comment by mikepenz** [comment] 2018-11-08 20:15
Hmm why not directly use vector drawables? they would always scale perfectly and are a lot smaller? 


The `ImageView` for the `PrimaryDrawerItem` has an effective size for the icon itself of 24x24dp
width = 56dp, paddingRight = 32dp
height = 48dp, paddingTop = 12dp, paddingBottom =12dp

no scaletype set

**Comment by tobybonhof** [comment] 2018-11-08 20:16
Sorry if i was not clear on that. I am using vector drawables: for example:

```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:fillColor="#FF000000"
      android:pathData="M11,13.5V21.5H3V13.5H11M9,15.5H5V19.5H9V15.5M12,2L17.5,11H6.5L12,2M12,5.86L10.08,9H13.92L12,5.86M17.5,13C20,13 22,15 22,17.5C22,20 20,22 17.5,22C15,22 13,20 13,17.5C13,15 15,13 17.5,13M17.5,15A2.5,2.5 0,0 0,15 17.5A2.5,2.5 0,0 0,17.5 20A2.5,2.5 0,0 0,20 17.5A2.5,2.5 0,0 0,17.5 15Z"/>
</vector>

```

**Comment by mikepenz** [comment] 2018-11-08 20:18
That should be perfectly fine. as you can see above the imageView has also the 24dp area for the icon.

**Comment by tobybonhof** [comment] 2018-11-08 20:18
But still it creates pixelated draweritem icons :(

**Comment by tobybonhof** [comment] 2018-11-09 06:39
Interesting.. well good to know it's probably not a library issue then. Not sure what is the issue. I'll try other things to fix.

**Comment by mikepenz** [comment] 2018-11-09 08:02
Still curious what might cause it. 

Can you try if you can somehow reproduce it in the sample app of this repo? Or create a sample app to showcase the issue, I might be able to have a look too

**Comment by tobybonhof** [comment] 2018-11-09 08:07
Okay I'll try and let you know

**Comment by tobybonhof** [comment] 2018-11-09 08:19
I managed to reproduce this in a bare minimum setup. I have zipped the code and attached it.
[android_drawer_test.zip](https://github.com/mikepenz/MaterialDrawer/files/2565112/android_drawer_test.zip)

**Comment by mikepenz** [comment] 2018-11-22 11:39
@tobybonhof were you able to figure something out? I still couldn't reproduce it on the phones I have available :/

**Comment by mikepenz** [comment] 2018-11-23 10:02
Could it be the phone? The emulator? Do you have other devices to test this with?

**Comment by tobybonhof** [comment] 2018-11-27 08:52
Sorry to get back so late. I had some other stuff to do. I was not able to figure out, what is happening. As most of the icons i use come from materialdesginicons.com I settled on using the built-in icon pack support for the drawer, this does not generate the pixelated effect. So i haven't quite fixed it, but the work around is good for me.

I have tested it on a Pixel 1, multiple genymotion emulators, Nexus 5, Nexus 5X, Oneplus 2. All same effect. It's probably some bug in the compiler that converts the xml to actual bitmaps on compile time. 

By the way the drawer is now in production, would you like to feature it on your github page?

**Comment by mikepenz** [comment] 2018-11-27 08:55
@tobybonhof yeah that is my assumption that it uses bitmaps instead of the actual vector. but even in that case it should not result in such a bad pixelated effect. blurry without sharp edges sure, but the way it looks in the screenshot is just weird. 

Still hoping somehow that we can find the root of this problem, as I am super curious :D


Oh awesome! :). Just open a PR and add it at the end of the list with apps using the drawer ;)

**Comment by mikepenz** [comment] 2018-12-15 15:39
Did you find anything new?

**Comment by mikepenz** [comment] 2019-01-19 17:05
Closing this now as it seems it is not happening for anybody else,  nor reproducible for me. 

If we get some more information or can find a way to reproduce let's reopen then.

**Closed by mikepenz** 2019-01-19 17:05 UTC
Labels: question
