### ISSUE TITLE
(AccountSwitcher) Circle Image and details

### ISSUE THREAD

**Issue by gaara87** [mikepenz/MaterialDrawer#36] opened 2015-02-26 01:30 UTC
Hey, first of this is an excellent start. Would love to be able to include this in the layout xml.

Suggestion: If you see the image in the url, there is a big circle profile picture along with Name and E-mail. It would be amazing to provide a layout a template for that. I could work on it if you accept pull requests.

http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7c2dhcFRZdzBPWnM/patterns_navdrawer_elevation1.png

**Comment by mikepenz** [comment] 2015-02-26 07:15
@gaara87 thanks.

Yeah i accept pull request ;). I'm always open for external input and improvements.

I've thought about this feature already, and i think it would make most sense to create a separate Header class (probably also with a builder) which will handle all the profile switching etc, and can then be passed to the drawer.

**Comment by sohayb** [comment] 2015-02-26 08:51
:+1:

**Comment by appmath** [comment] 2015-02-26 17:27
I love this idea. Please take into consideration the fact that some users might have only one account and the drop down is not necessary.

**Comment by gaara87** [comment] 2015-02-26 23:33
Well a Builder class seems like a good idea to interact with the construction of it.

I'm thinking of having it as a separate HeaderFragment only because it seems like it seems like its got enough functionality just within it.

Also, if you were already planning to work on it, then i guess we can see which part of it i can contribute to

**Comment by mikepenz** [comment] 2015-02-27 08:29
@gaara87 yeah i haven't started yet. just made a few notes yesterday after searching for all details. I've found that it seems no lib solves it like it's done within Google Play or Google Plus yet. I would try to implement such a behavior including changing the list if you click the select-box.

;)

**Comment by appmath** [comment] 2015-02-27 17:23
You might want to take a look at https://github.com/neokree/MaterialNavigationDrawer, specifically 
circularPhoto = new BitmapDrawable(resources,Utils.getCroppedBitmapDrawable(photo));
in the Utils class. 
I also like the animation when the user switches accounts (by clicking on one of the 2 photos on the right).

![image](https://cloud.githubusercontent.com/assets/4098053/6417447/ae29b6b2-be6a-11e4-9acf-9d4f3e17f3e6.png)

**Comment by gaara87** [comment] 2015-02-27 17:57
@appmath That Util class for the cropped drawable does look nice :)

I was just going to use https://github.com/hdodenhof/CircleImageView since it is a pretty good library already.

I was thinking of simply creating a viewpager (maybe an infinite looping one, or maybe one that only swipes from left to right and no right to left interaction) for for being able to switch the accounts, thats all :) Maybe an infinite viewpager. I love way google drive & inbox handle the transition.

**Comment by mikepenz** [comment] 2015-02-27 18:25
@appmath so i have the basic layout. and a basic builde. now i just need to implement the special drawerItems for the accounts and the functionality

**Comment by appmath** [comment] 2015-02-27 19:47
Wow! That was fast. OK, I am going to take a look at the "fruits" of your efforts.
Thanks

**Comment by mikepenz** [comment] 2015-02-27 21:53
@appmath, @gaara87 some more updates to this branch and the source. basic switching with the images is possible now. next is the list for all profiles.

**Comment by gaara87** [comment] 2015-02-28 01:27
@mikepenz thats awesome! looks like you are dedicating quite a bit of time to it :) wish i had the time to do it too :+1:

**Comment by jiechu** [comment] 2015-02-28 09:59
Can you please merge this feature to master branch then post to maven central?

**Comment by mikepenz** [comment] 2015-02-28 15:28
It is not yet ready. As soon as everything is in and working it will be
merged ;)

jiechu <notifications@github.com> schrieb am Sa., 28. Feb. 2015 10:59:

**Comment by mikepenz** [comment] 2015-03-01 14:36
@appmath @gaara87 @jiechu @sohayb some teasering :stuck_out_tongue: 


![screenshot_2015-03-01-15-33-36](https://cloud.githubusercontent.com/assets/1476232/6431210/93111a90-c028-11e4-90da-fd013e6cc5c1.png)
![screenshot_2015-03-01-15-33-42](https://cloud.githubusercontent.com/assets/1476232/6431209/9140adac-c028-11e4-9072-32160c235628.png)
![screenshot_2015-03-01-15-35-58](https://cloud.githubusercontent.com/assets/1476232/6431214/b7f2c476-c028-11e4-95aa-d8807d410e03.png)

**Comment by mikepenz** [comment] 2015-03-01 14:50
@appmath @gaara87 @jiechu @sohayb 

In preparation of a stable launch i hope everyone who is interested in this feature is part of some initial testing. To create a test the initial preview i've uploaded a preview version of the library to the SNAPSHOT repository of maven. 

Just add the snapshot repository to your repositories within the main `build.gradle` under 'allprojects`
```javascript
maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
```

After this add the following compile dependency:

```javascript
compile('com.mikepenz.materialdrawer:library:1.5.0-SNAPSHOT@aar') {
        transitive = true
}
```

Now you can use the AccountDrawer.  To see the basic setup and how to use it take a look at following class:

https://github.com/mikepenz/MaterialDrawer/blob/accountswitcher/app/src/main/java/com/mikepenz/materialdrawer/app/SimpleDrawerActivity.java

What you have to do:
1. Create the AccountHeader
2. Create the Drawer and pass the AccountHeader result

//DONE :D

And here's a working sample of the drawer to check it out ;). 
http://weew.ee/dfnPL


Please report all errors, bugs, missing helper methods within the result in this thread.

**Comment by sohayb** [comment] 2015-03-01 15:40
Awesome! :+1: 
Will test it as soon as I can, too sucked up in C# now :( :P

**Comment by khammami** [comment] 2015-03-02 09:39
I've tested it and it works! Good woork @mikepenz 

well at the begining I got this error :
>java.lang.NoSuchFieldError: No static field account_header_drawer of type I in class Lcom/mikepenz/materialdrawer/R$id; or its superclasses (declaration of 'com.mikepenz.materialdrawer.R$id' appears in /data/app/com.khammami.settaghram-1/base.apk)
            at com.mikepenz.materialdrawer.accountswitcher.AccountHeader.build(AccountHeader.java:316)

I got this error because it appears that I used a lyaout name already used in your library which is "drawer_header"

![screenshot_2015-03-02-10-35-18](https://cloud.githubusercontent.com/assets/297917/6438334/519256c4-c0c8-11e4-994c-6bfb22160367.png)

**Comment by mikepenz** [comment] 2015-03-02 14:39
@khammami thanks for testing. 

oh that's bad, probably i should rename the layout to prevent this. 

another thing. It seems you don't use a translucent statusbar have you disabled the translucent statusbar within your drawer? because the header's height is to high. 

Please use `withTranslucentStatusBar(false)` for the AccountHeader and your Drawer

**Comment by fdorssers** [comment] 2015-03-02 15:03
I downloaded the latest version from the accountswitcher branch to give it a go and look at the sample app. First of all, I really it. But I did notice a small bug in the sample app.

If I open the app I'm in the settings part of the app, which can be seen by [this toast](https://cloud.githubusercontent.com/assets/5364280/6443106/03724fd0-c0f5-11e4-9639-3f1bdfda417d.png) and the fact that the settings item [is selected](https://cloud.githubusercontent.com/assets/5364280/6443138/311d25ae-c0f5-11e4-9118-75b32368d0d9.png). If I then open the [list of accounts](https://cloud.githubusercontent.com/assets/5364280/6443152/4befd548-c0f5-11e4-9774-7a3c9a7bf46b.png) and close it, then the help section [is selected](https://cloud.githubusercontent.com/assets/5364280/6443165/5e1b3668-c0f5-11e4-8f05-eee221097284.png). Even though it is unclickable.

**Comment by khammami** [comment] 2015-03-02 17:47
@mikepenz  yeah I think you should add a prefix for the layouts to avoid this kind of error.

you're right about the height of the header I'm using a theme with no translucent statusbar. I disabled it in the header and the drawer  as you said, it's look fine now thanks :+1:

**Comment by mikepenz** [comment] 2015-03-02 18:28
@fdorssers yeah you are right. will fix it with the next test release ;)

@khammami that's true. will prefix it ;). Great ;) makes a difference. i think it would be nice if the drawer used the value you set for the header :D makes sense that both specify the same translucentStatusBar value

**Comment by mikepenz** [comment] 2015-03-02 20:32
@appmath @gaara87 @jiechu @sohayb @fdorssers @khammami 

so i think i've fixed all issues reported here. and added some new stuff (which probably shouldn't be in this branch but yeah)

- prefix material_drawer layouts
- fix issue with wrong selection after open / close profile selector
- no more ActionBarDrawerToggle animation by default
- add methods to store/load instancestate for ProfileHeader (in fact it's just the selection)
- colors are now defined by the theme. --> if you use a dark theme -> dark drawer, light theme -> light drawer ;). 
  - overwrite those colors like you would in previous versions, with one difference. if you use a dark theme you have to overwrite the dark colors. if you want it clean then just create a custom theme by extending one of my themes and overwrite one of the following values

```xml
        <item name="material_drawer_window_background">@color/material_drawer_dark_window_background</item>
        <item name="material_drawer_background">@color/material_drawer_dark_background</item>
        <item name="material_drawer_icons">@color/material_drawer_dark_icons</item>
        <item name="material_drawer_primary_text">@color/material_drawer_dark_primary_text</item>
        <item name="material_drawer_secondary_text">@color/material_drawer_dark_secondary_text</item>
        <item name="material_drawer_hint_text">@color/material_drawer_dark_hint_text</item>
        <item name="material_drawer_divider">@color/material_drawer_dark_divider</item>
        <item name="material_drawer_selected">@color/material_drawer_dark_selected</item>
        <item name="material_drawer_selected_text">@color/material_drawer_dark_selected_text</item>
        <item name="material_drawer_header_selection_text">@color/material_drawer_dark_primary_text</item>
```

I would be happy if you could test it again. Please let me know which methods are still missing to have everything you need for implementing this in your applications.

**Comment by fdorssers** [comment] 2015-03-02 20:57
Awesome! I did notice two more bugs. It breaks if you open the profile selector and press on different profiles very quickly. The drawer turns white and after opening the profiles once they won't go away anymore. The other bug is if there's only one account the downwards pointing arrow on the profile header isn't visible.

In terms of features it would be nice to have log in or log out buttons in the profile section of the drawer that we can override. Meaning that if the user pressed the log in button we could call our own RESTful service and then return for example a new profile with the relevant data that would then be added to the drawer. It would also be nice to have a small log in reminder on the header if no profiles are added. For example simply 'Log in' as the profile name and if you click on it the profile part opens with the log in button.

**Comment by mikepenz** [comment] 2015-03-02 21:03
@fdorssers thanks for the detailed report ;)
about the quick profile switch. yeah you are right. i hope i can somehow block this. :/ 
it's a feature. :D it makes no sense to show the profile switching list if there'S only one profile. but in combination with the features you would love to see it makes sense :D

do you mean something like it's done within gmail?
there are an add account and manage accounts button below the profile list. this would be possible i think. still with the same logic as it's now and you can then pass the new account to the AccountHeader.Result. 

i just saw that gmail allows badges for the accounts in the list. anyone requires them?

**Comment by fdorssers** [comment] 2015-03-02 21:17
@mikepenz I see what you're getting it, it wouldn't make sense with only one profile, but it can still be opened with only one profile. So that should probably also be disabled then to make it consistent with the lack of the arrow. 

Gmail is an example yes. Although a specific 'manage account' option probably wouldn't be needed. Basically you could for example (1) add a 'log out' button in the profile list for the current account or (2) add X's to the right of the profiles to log out. I edited my question right before you answered to include Reddit News as an example, which includes these options.

**Comment by mikepenz** [comment] 2015-03-02 21:21
@fdorssers haha oh i missed this one. you are right ;)

I think i'm probably a bit more safe if i also allow custom ProfileItems within the AccountHeader so the dev can extend it if he really needs such an log-out button or a "X" on the right. this will allow many customizations and still keep the base of the MaterialDrawer small and simple (or at least the api :D)

oh didn't see this one. do you have a screenshot?

**Comment by fdorssers** [comment] 2015-03-02 21:36
Awesome idea :) . 

[This](http://imgur.com/a/kAjiv) album shows how it works in Reddit News.
- Initially you are not logged in. You get buttons to log out or add an account (log out probably being a bug)
- Once you have added an account it also logs you in
- Showing the profiles shows the previous options (log out and add account). If you press log out then it logs you out but the account still exists. If you want you can log back in by clicking the account name
- Pressing the X completely removes the account from the app and logs you out.

Obviously it's just an example. I can't think of many instances where having accounts but not being logged in is useful. So your log out could for example immediately remove the account too. But that's all up to you :) .

**Comment by mikepenz** [comment] 2015-03-02 21:47
@fdorssers thanks for the album.

interesting behavior in the reedit news app :D 

in fact it's not up to me. :D it's up to the dev. my task is to provide the best or easiest api possible to implement such a behavior :D.

so if i implement a ProfileItem interface which can be used to create custom items many tasks are already in :D. then it will also require an api to set non profile elements for the selection, but yeah ;). 

so my next steps are:

- implement an interface for the AccountHeader selection list items
- implement the method calls to add new Items to the AccountHeader list on demand
- Add option to disable the selection list if there is only one item

**Comment by tarikyurtlu** [comment] 2015-03-02 22:14
@mikepenz firstly thank you for great meterialDrawer Library. I did test with version com.mikepenz.materialdrawer:library:1.5.0.PREVIEW.2-SNAPSHOT@aar 
but I found two bugs. Other friends explained this bugs. But I want to property for AccountHeader. I don't want clicking. For example : setEnableCicking (false). I have not seen this feature.  ??

Thanks,
Tarık

**Comment by gaara87** [comment] 2015-03-03 00:09
All tests seemed to be working just fine for me :+1: awesome!!!

**Comment by mikepenz** [comment] 2015-03-03 07:05
@tarikyurtlu you want the AccountHeader to be not clickable? I'm not quite sure about the real issue here? The header itself is not clickable only the images and the selection.

@gaara87 thanks

**Comment by tarikyurtlu** [comment] 2015-03-03 18:25
@mikepenz  Thanks for answer. Yes, I want the AccountHeader to be not clickable. (Maybe can be property, for example setEnableCicking (false)) Maybe Images and the selection is not clickable. (setEnableCicking (false)) . Actually  I just want to show  circle pictures , username and e-mail. Is it possible ? 

Thanks,
Tarık

**Comment by mikepenz** [comment] 2015-03-03 18:31
@tarikyurtlu you want to show the profile images as normal but without the possibility to switch profiles with this function. the selection should also be disabled. i see. 

yeah i think with the next things i've planned this will also be possible :D

**Comment by khammami** [comment] 2015-03-03 19:41
Hey @mikepenz, with the second preview everything seems ok right now :D 

but I've some remarks : 
* When you change the header height, the account list selector should stick in the bottom of the header which is not the case in your implementation right now.
* for the header background, I think it will be good to let the dev to choose the scale type. for example In my case I use square image from instagram, so fit-xy it would not be nice. for that it's better for me to use fit only on x and crop center on y.
* I think also you need to add some shadow for circular profile picture to follow material design guide, it's ok with simple background but with other it's better to show some depth (z)
* It would nice to add a changelog so other can follow easily the changes.

thanks :)

**Comment by mikepenz** [comment] 2015-03-03 22:32
@khammami thanks ;)

- you mean a compact header? or what do you mean?
  - this one is planned :D
- method added in next preview
- elevation functionality added to circularImageView is in for Lollipop devices
- will start to write changelogs starting with the final release of this version ;)

**Comment by mikepenz** [comment] 2015-03-03 22:48
@appmath @gaara87 @jiechu @sohayb @fdorssers @khammami, @tarikyurtlu 

and another PREVIEW version. thank you all for helping and for testing. 

fixed a few issues and added new stuff.

(just as a reminder :D) you can get it by following the above description: https://github.com/mikepenz/MaterialDrawer/issues/36#issuecomment-76599969
but using the following as dependency
```javascript
compile('com.mikepenz.materialdrawer:library:1.5.0.PREVIEW.3-SNAPSHOT@aar') {
        transitive = true
}
```

A small changelog within this (rather dirty) commit :D
https://github.com/mikepenz/MaterialDrawer/commit/c49b823a0c12757471e297a99530cf1b0e78517d


- Open Issues
  - if i click really fast on the items the list stays blank. (i got no idea :P)
  - more helper methods for the header
  - compact header view

**Comment by appmath** [comment] 2015-03-04 02:06
@mikepenz 
Hello Mike,
Versions used: PREVIEW 2 and PREVIEW 3. 
I just found a minor issue, the section header without a title looks odd (screenshot). 
![sectionheader](https://cloud.githubusercontent.com/assets/4098053/6476838/27e7c118-c1d8-11e4-8a0d-6f691952d345.png)

I love how a single account looks. 
Thanks

**Comment by mikepenz** [comment] 2015-03-04 07:47
@appmath if you need an empty section header use a divider item ;)

**Comment by khammami** [comment] 2015-03-04 09:59
@mikepenz  now there is some bugs but let me explain what I meant in my last comment with a screenshot:

![image](https://cloud.githubusercontent.com/assets/297917/6480986/abba5844-c259-11e4-921c-476182d50f0d.png)

as you can see, the header's content stay on the top of the layout when someone change header's height. In my opinion it should stay in bottom of the layout especially for text.

For the third preview, I used your code to test the new features:

>new ProfileSettingDrawerItem().withEmail("Add Account").withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_add).paddingDp(5)),

the result :

* there is a black box, I had 2 profile now I have 3 including the black box :D 
* when you switch between profiles look what happens to add icon

![image](https://cloud.githubusercontent.com/assets/297917/6481131/2145587e-c25b-11e4-82f3-75a443c975c2.png)

![image](https://cloud.githubusercontent.com/assets/297917/6481242/15dfe91c-c25c-11e4-9f1b-a3e1d19325f0.png)


then when I use normal add icon without defining a new icon with padding :

>new ProfileSettingDrawerItem().withEmail("Add Account").withIcon(GoogleMaterial.Icon.gmd_add)),

result :

![image](https://cloud.githubusercontent.com/assets/297917/6481288/7aa5f7ce-c25c-11e4-89ff-42b970708650.png)

![image](https://cloud.githubusercontent.com/assets/297917/6481322/c090fbbc-c25c-11e4-8c0b-d908d7489040.png)

now there is circular shadow when you select it the add icon disappear

I used CENTRER_CROP for scale type now it's better thanks

by the way, I'm using a nexus 4 (5.0.1) for testing but I have also a nexus s I'll test the drawer on it later ;)

**Comment by timgreen** [comment] 2015-03-04 10:13
@mikepenz thanks for this awesome library. Do you plan to support modify profile items in the headerResult? In my app, the list of profile might be changed after sync.

**Comment by mikepenz** [comment] 2015-03-04 10:56
@khammami will take a detailed look later today. 

This line has a bug
```java
new ProfileSettingDrawerItem().withEmail("Add Account").withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_add).paddingDp(5)),
```
i missed the `.actionBarSize()`

@timgreen yeah is planned i just have to add the helper methods

**Comment by fdorssers** [comment] 2015-03-04 16:10
@mikepenz I put in a pull request for the previously mentioned bug that occurred when switching profiles quickly.

The issue that @khammami has is caused by the fact that the drawer tries to show three profiles in the header even though not all the profile items are actually profiles. In `AccountHeader.java` the function `buildProfiles()` builds the little icon previews. However it doesn't check if the item with the profile interface is a `ProfileDrawerItem` or a `ProfileSettingDrawerItem`.

This can fixed by adding that check to the code, for example 
```Java
if (mProfileFirst != null && mProfileFirst instanceof ProfileDrawerItem) {
    ...
}
if (mProfileSecond != null && mProfileSecond instanceof ProfileDrawerItem) {
    ...
}
```
Should fix it for the small icons. If you want devs to be able to create their own profile drawer items it might be handy to add a new function that they can override to specify whether or not to show it. Or whatever way would suit you :) .

**Comment by mikepenz** [comment] 2015-03-04 19:22
@fdorssers yeah thanks again for the pull request ;)

yeah the problem was not in the buildProfiles but in the build method which calculates the first 4 profiles to set. i've fixed this now.

about the solution for the fix. there is already a method which allows the devs to set a specific item selectable :D 

the complete solution is this
```java
//set the active profiles
        if (mProfiles != null) {
            int setCount = 0;
            for (int i = 0; i < mProfiles.size(); i++) {
                if (mProfiles.size() > i && mProfiles.get(i).isSelectable()) {
                    if (setCount == 0) {
                        mCurrentProfile = mProfiles.get(i);
                    } else if (setCount == 1) {
                        mProfileFirst = mProfiles.get(i);
                    } else if (setCount == 2) {
                        mProfileSecond = mProfiles.get(i);
                    } else if (setCount == 3) {
                        mProfileThird = mProfiles.get(i);
                        break;
                    }
                    setCount++;
                }
            }
        }
```

all items which implement the `IProfile` interface have to implement `.isSelectable()` which defines if the profile is a selectable profile ;)

**Comment by mikepenz** [comment] 2015-03-04 21:11
@appmath @gaara87 @jiechu @sohayb @fdorssers @khammami, @tarikyurtlu 

and another (and hopefully the last) PREVIEW version. thanks again for helping and for testing. 

another batch of fixed issues and new method calls

(just as a reminder :D) you can get it by following the above description: https://github.com/mikepenz/MaterialDrawer/issues/36#issuecomment-76599969
but using the following as dependency
```javascript
compile('com.mikepenz.materialdrawer:library:1.5.0.PREVIEW.4-SNAPSHOT@aar') {
        transitive = true
}
```

- Open Issues
  - compact header view

**Comment by mikepenz** [comment] 2015-03-04 22:08
ok it seems i lied :D 

i hope it's ok for everyone that there's another update with a compact header style and with a small fix to align the select box to the bottom if the height of the header is changed.

```javascript
compile('com.mikepenz.materialdrawer:library:1.5.0.PREVIEW.5-SNAPSHOT@aar') {
        transitive = true
}
```

- Open Issues
  - as far as i know none :D

**Comment by fdorssers** [comment] 2015-03-04 23:12
Looking good! But I did find another bug. I took the example app and removed all profiles except for the first one:
```Java
.addProfiles(
    profile,
    // profile2,
    // profile3,
    // profile4,
    // profile5,
    //don't ask but google uses 14dp for the add account icon in gmail but 20dp for the normal icons (like manage account)
    new ProfileSettingDrawerItem().withEmail("Add Account").withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_add).actionBarSize().paddingDp(5)).withIdentifier(1),
    new ProfileSettingDrawerItem().withEmail("Manage Account").withIcon(GoogleMaterial.Icon.gmd_settings)
)
```
And created a button to add profile2:
```Java
findViewById(R.id.add_profile).setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        headerResult.addProfile(new ProfileDrawerItem().withName("Max Muster").withEmail("max.mustermann@gmail.com").withIcon(getResources().getDrawable(R.drawable.profile2)), 0);
    }
});
```
However this kinda messes up the icons as can be seen in [this](https://cloud.githubusercontent.com/assets/5364280/6495532/74c91cd6-c2cb-11e4-95ce-aa81cf699b59.png) and [this](https://cloud.githubusercontent.com/assets/5364280/6495542/8388d748-c2cb-11e4-815a-9cd0d3ba5012.png) screenshot.

It appears to have to do with the order. Adding it on position 1 instead of 0 works. The same occurs when you already have two items. If you don't add it at the end it goes wrong.

And I have one more stylistic remark: Picking a profile from the profile section shows you that the profiles switch in the header because there's a delay on the closing. However when you click the icons in the header the drawer closes immediately and you can't immediately see whether it has switched. I think it would be nice and consistent if the drawer also had a delay of half a second when using these icons to switch profiles.

**Comment by khammami** [comment] 2015-03-05 12:23
@mikepenz you're allmost there :) just few more tweaks:

* the selection list on JB 4.1.2 need some space check [this screenshot](https://cloud.githubusercontent.com/assets/297917/6504382/e250fc90-c336-11e4-9dfe-2ef69e8f2e44.png) and [this one](https://cloud.githubusercontent.com/assets/297917/6504687/2a7a6f58-c33a-11e4-8710-7df46c28754d.png)
 for Lollipop.
* in the same screenshots, I didn't put a picture for the profile so I think you should add a default icon for that.
* one more request for single profile only, is it possible to add a feature to disable profile icon (only text without a profile image) and another option to disable the selection list default behavior: for example when a user click on the selection list, instead of getting a list with only one profile or maybe options to manage his profile it take him to his profile in the app with a custom listener

**Comment by fdorssers** [comment] 2015-03-05 12:49
@mikepenz I found another small bug. At the moment if there's a single actual profile you can still use the selection list. No issue there as you can always enable/disable it with the following two lines:
```Java
.withSelectionListEnabled(true)
.withSelectionListEnabledForSingleProfile(true)
```
However if my only item is the log in button (from the example of yours) then I can't get the list to show, even using the two options above.

And your previous fixes have created another small issue. If there's only a single option in the selection list, for example 'log in', then it would be nice to have this show up as the 'current profile', to show people where to click to log in. So if they click it the normal selection list could open with the options.

**Comment by timgreen** [comment] 2015-03-05 13:31
@mikepenz 

I found an issue with profiles modification.

During drawer setup, I added one profile A. Later after call `headerResult.setProfile([B, C, D, E)`, I found the profile A is still there.

A fix will be change `calculateProfiles` to 

~~~
protected void calculateProfiles() {
  IProfile[] previousActiveProfiles = new IProfile[] {
    mCurrentProfile,
    mProfileFirst,
    mProfileSecond,
    mProfileThird
  };
  
  IProfile[] newActiveProfiles = new IProfile[4];
  Queue<IProfile> unusedProfiels = new Queue<>();
  
  // try to keep existing active profiles in the same positions
  for (int i = 0; i < mProfiles.size(); i++) {
    IProfile p = mProfile.get(i)
    if (p.isSelectable()) {
      boolean used = false;
      for (int j = 0; j < 4; j++) {
        if (previousActiveProfiles[j] == p) {
          newActiveProfiles[j] = p;
          used = true;
          break;
        }
      }
      if (!used) {
        unusedProfiels.push(p);
      }
    }
  }
  
  Queue<IProfile> activeProfiles = new Queue<>();
  // try to fill the gaps with new available profiles
  for (int i = 0; i < 4; i++) {
    if (newActiveProfiles[i] != null) {
      activeProfiles.push(newActiveProfiles[i]);
    } else if (!unusedProfiels.isEmpty()) {
      activeProfiles.push(unusedProfiels.pop());
    }
  }
  
  // reassign active profiles
  if (activeProfiles.isEmpty()) {
    mCurrentProfile = null;
  } else {
    mCurrentProfile = activeProfiles.pop();
  }
  if (activeProfiles.isEmpty()) {
    mProfileFirst = null;
  } else {
    mProfileFirst = activeProfiles.pop();
  }
  if (activeProfiles.isEmpty()) {
    mProfileSecond = null;
  } else {
    mProfileSecond = activeProfiles.pop();
  }
  if (activeProfiles.isEmpty()) {
    mProfileThird = null;
  } else {
    mProfileThird = activeProfiles.pop();
  }
}
~~~


And is there a way to show both name & email in the profile selection list?

**Comment by mikepenz** [comment] 2015-03-05 20:19
@appmath @gaara87 @jiechu @sohayb @fdorssers @khammami, @tarikyurtlu, @timgreen 

special thanks to @timgreen for the nice calculateProfiles method (had some bugs in it but yeah it basically it was the right thing ;) )


so this time there isn't a changelog too. to many changes. I hope i was albe to hunt down most or all mentioned bugs. if i missed something let me know. The header now allows really really many different options :D haha

```javascript
compile('com.mikepenz.materialdrawer:library:1.5.0.PREVIEW.6-SNAPSHOT@aar') {
        transitive = true
}
```

**Comment by fdorssers** [comment] 2015-03-05 21:26
@mikepenz you're really putting some impressive work into this. At the moment I haven't found any bugs yet. And good idea on adding the removeProfile option. I'm sure many of us would've encountered that at some point in time.

I do have one more stylistic / functionality suggestion, but I couldn't find the specifics in the material documents. I think it would be nice and intuitive if the icons at the top would represent the three most recently used profiles in the right order. At the moment if you have profiles 1 2 and 3 and you press 3 then 1 and 3 will switch, putting the icons in the order of 3 2 1. My suggestion would be to then make it 3 1 2. Or if you have the accounts 1 2 3 as icons and another account 4 in the drawer, if you press 4 you get 4 2 3, instead of 4 1 2. If you get what I mean.

**Comment by mikepenz** [comment] 2015-03-05 21:42
@fdorssers ok that's good. i hope that this preview will solve most things. have you tried the compact header style?

yeah i see what you mean. something nice would be that it automatically stores this information over app restarts, and activity recreations :D.

**Comment by mikepenz** [comment] 2015-03-06 12:43
@appmath @gaara87 @jiechu @sohayb @fdorssers @khammami, @tarikyurtlu, @timgreen

Any arguments against a final release of the Header today?

**Comment by appmath** [comment] 2015-03-06 13:00
I have looked at the latest release and I didn't find any issues (my exploratory use case is "lighter" than other people). This weekend, I am going to start working on some serious ("heavier") integration with my current project.

It looks good to me.

Thanks Mike and....excellent job!!!

**Comment by tarikyurtlu** [comment] 2015-03-06 13:06
Hi Mike , I didn't find any issue as per last version.

Thanks for support.  :)
6 Mar 2015 15:01 tarihinde "appmath" <notifications@github.com> yazdı:

**Comment by fdorssers** [comment] 2015-03-06 13:59
@mikepenz I had a look at the compact drawer and everything seems to work fine. Other than my current open issue it looks like everything is okay :) .

**Comment by mikepenz** [comment] 2015-03-06 19:22
@appmath @gaara87 @jiechu @sohayb @fdorssers @khammami, @tarikyurtlu, @timgreen

Thanks everyone for helping me to test this huge release. 

v2.0.0 was pushed to maven central a few moments ago. 
Please note that the final release of v2.0.0 contains a few naming changes of some methods, and a naming change from the DarkActionBar theme to DarkToolbar. Beside this i added the method descriptions to the wiki, and made a few more tiny fixes. 

I hope you like it ;)

If there are any features left or something missing, please create a new issue.

**Closed by mikepenz** 2015-03-06 19:22 UTC
Labels: enhancement

**Comment by blennerSilva** [comment] 2015-09-12 14:15
hey mike do you think you could help me? i need to load an image from gallery as a prifile pic...could you help me ?

**Comment by mikepenz** [comment] 2015-09-12 14:16
@blennerSilva you can set an url, drawable, bitmap as profile pic. so if you get the image as bitmap or drawable from the gallery you can set this. i assume you will have to load the image in an asyncTask and as soon as you got it you can set it

**Comment by blennerSilva** [comment] 2015-09-12 14:26
but thats only possible in the new version of the library or in all of them ? im using this one
  compile('com.mikepenz.materialdrawer:library:2.8.2@aar') {
        transitive = true
    }

**Comment by mikepenz** [comment] 2015-09-12 14:27
@blennerSilva sorry i can't give support for versions different than the most current one.
