### ISSUE TITLE
ActionBar/Toolbar menu items displaying twice

### ISSUE THREAD

**Issue by bmsgarces** [mikepenz/MaterialDrawer#505] opened 2015-07-22 15:18 UTC
The same thing filipebezerra posted on neokree MaterialNavigationDrawer is happening to me.

See: https://github.com/neokree/MaterialNavigationDrawer/issues/254

Any thoughts on this?

**Comment by mikepenz** [comment] 2015-07-22 16:43
@filipebezerra @bmsgarces what are you doing to get this issue? i never had this one or i never saw this one?

I assume it could be related to the android appcompat library. I do not do anything with the menu. so i'm sure this is not related to the MaterialDrawer

**Comment by filipebezerra** [comment] 2015-07-22 17:22
Yeap I thing that issue is related with the support library.

To simulate that all you have to do is to include a menu resource file within a item as showAsAction=always to always see it in ActionBar. And when the menu is inflated, press the the menu softkey.

To replace that behavior, I override the onKeyUp in the activity, then handling the KeyEvent.KEYCODE_MENU to open the Drawer.

**Comment by filipebezerra** [comment] 2015-07-22 17:26
The issue is, when the menu item is shown in the ActionBar (or in Overflow menu), pressing the menu softkey, then the menu is shown above the navigation bar with the same menu visible at ActionBar.

**Comment by mikepenz** [comment] 2015-07-22 17:28
@filipebezerra yeah sorry that i can't help here. but perhaps it is fixed in one of the next appcompat updates

**Closed by mikepenz** 2015-07-22 17:28 UTC
Labels: question

**Comment by bmsgarces** [comment] 2015-07-22 17:34
Well, thanks for the input filipe.

**Comment by filipebezerra** [comment] 2015-07-22 17:41
Thanks for you guys

**Comment by droidizer** [comment] 2016-01-14 10:11
I'm facing the same issue. :(

**Comment by mikepenz** [comment] 2016-01-14 10:26
@droidizer what do you mean?

**Comment by droidizer** [comment] 2016-01-14 10:29
Menu items are appearing twice but I can't figure out why.

**Comment by mikepenz** [comment] 2016-01-14 10:31
@droidizer do you use the latest appcompat? the latest version of this library? have you tested it in the emulator? can you try it with a new activity only containing stuff (perhaps just copy the sample activity) if it still happens?

**Comment by droidizer** [comment] 2016-01-14 11:01
Yes I have used the latest appcompat library. 
I have been testing on the devices. What I'm trying to do is, inflate the menu in the MainActivity and try to use a MenuProvider interface for different fragments which provides the menu object.
