### ISSUE TITLE
(MiniDrawer) Selected item row_selector shown for 2 rows at the same time

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/MaterialDrawer#1047] opened 2016-02-29 13:45 UTC
I have MiniDrawer without account header and have this issue(first screenshot): 2 rows are selected at the same time. It became broken after 5.0 update.

Another issue is that when drawer is opened some top padding is added (second screenshot). This also became broken after 5.0 update.

![screenshot_20160229-173725](https://cloud.githubusercontent.com/assets/1249919/13396049/dff67e92-df0b-11e5-9042-39c7db27666d.png)

![screenshot_20160229-173729](https://cloud.githubusercontent.com/assets/1249919/13396048/dfdadb92-df0b-11e5-8304-8786a3a05338.png)

**Comment by mikepenz** [comment] 2016-02-29 17:22
@androideveloper the first is fixed in the next update. 
for the second provide just the following to the `DrawerBuilder`
```java
.withDisplayBelowStatusBar(false)
```

**Closed by mikepenz** 2016-02-29 17:22 UTC
Labels: bug, question

**Comment by androideveloper** [comment] 2016-03-01 07:24
@mikepenz Thanks, these cases are fixed. But before update to 5.0 library was more stable..When I was randmly selecting items in MiniDrawer, it was faster than now (I see some lags now). Also while random selecting items, I meet the case when no item is become selected..

**Comment by androideveloper** [comment] 2016-03-01 07:48
@mikepenz I have a question regarding .withDisplayBelowStatusBar(). It seems that you changed the meaning of this function since 5.0 update (Do the right opposite). Is the doc right "Sets that the slider of this Drawer should be displayed below the statusBar even with a translucentStatusBar" ? Cause I understand, if the doc is true, I should set this to "true" (and padding will not be added). But on the practice "false" is what I want. Please, provide some details on this

**Comment by mikepenz** [comment] 2016-03-01 07:54
@androideveloper with the v5.x.x update the drawer no longer manages the `padding`s those are now defined by the `fitsSystemWindows` flag. so in general all behaviors are controlled via this flag and the system. 

As the docs state for the `withDisplayBelowStatusBar()`
> Sets that the slider of this Drawer should be displayed below the statusBar even with a translucentStatusBar
this method will remove the padding on top if set to `true`


--------------------

v5.x.x is more stable. There is no lag. It just animates the previous item when deselected. The new selected item is selected instantly.
I also was not able to reproduce this even with clicking very fast, there was always a selection

**Comment by androideveloper** [comment] 2016-03-01 08:23
@mikepenz ok, thanks. So "this method will remove the padding on top if set to true" but in your previous comment you said ".withDisplayBelowStatusBar(false)".  So which one is right to remove top padding from recyclerview?  (" false" works for me)

**Comment by androideveloper** [comment] 2016-03-01 08:35
Here is video
https://youtu.be/lFOYMlTQWxE?t=6s
