### ISSUE TITLE
Bug when setting .withProfileImagesVisible(false) in MiniDrawer

### ISSUE THREAD

**Issue by toastking42** [mikepenz/MaterialDrawer#1207] opened 2016-04-21 16:57 UTC
Hi,

first I want to say thank you for this great library!

I have created an activity that uses the MiniDrawer just like in the example application.
Because of the fact that I don't have profile images associated with the accounts, I hide them using  .withProfileImagesVisible(false) when initializing the AccountHeader. The drawer itself contains just some PrimaryDrawerItems.

This is working perfectly fine up until the point where the user uses the account selection to select another account. The MiniDrawer then hides the first PrimaryDrawerItem while in the expanded NavigationDrawer, it's still shown. In the MiniDrawer, where the first PrimaryDrawerIcon that is now missing used to be, there is just empty space (like View.INVISIBLE, not like View.GONE)

For testing purposes, I added an icon to the accounts despite the fact that I don't normally do it. By doing this, I found out that the MiniDrawer draws the Icon associated with the chosen account over the first PrimaryDrawerItem despite withProfileImagesVisible being set to false. This does only happen as soon as another account is selected. When no icon has been set for the account, it seems to just draw an empty view (?) that sits on top of my first PrimaryDrawerItem.

Would it be possible to get this fixed soon?

**Comment by mikepenz** [comment] 2016-04-21 19:09
@toastking42 I will have to reproduce it first in the sample, and then I will implement a fix. I should have some time for this tomorrow evening.

**Comment by toastking42** [comment] 2016-04-22 06:45
Hi Mike,

thanks for the swift reply!
I've cloned your repository and added 
` .withProfileImagesVisible(false)`
after line 78 of your MiniDrawerActivity.java.

In this case, the setting seems to be ignored right from the beginning, because in the MiniDrawer, the profile image is shown at the top. In the expanded drawer, no profile pictures are visible. That doesn't seem right either?

The overdrawing of DrawerItems like I described in my previous post seems to be happening because when I initially add the drawer and MiniDrawer, no accounts are associated with them, they are only added after an asynchronous task has finished.
You can reproduce my exact problem by first adding the abovementioned code after line 78, then commenting out lines 80 to 90 (where the profiles are added) and moving these lines to the end of the onCreate() method, i.e. inserting it after:

`crossFader.getCrossFadeSlidingPaneLayout().setShadowResourceLeft(R.drawable.material_drawer_shadow_left);`

Then start the Activity and choose another account in your drawer's device chooser. The first item will be hidden by a profile image.

**Comment by mikepenz** [comment] 2016-04-22 18:39
I can't reproduce the overdrawing, but i have fixed the issue that the profile is shown even if disabled
will be in the next release

**Closed** 2016-04-22 18:39 UTC
Labels: bug

**Comment by toastking42** [comment] 2016-04-22 22:24
Thanks Mike.
Since ideally I'd need the drawer to function correctly now, is there any quick fix in my code that I could use until the new version is released? For example, reinitializing the drawer in some way.

**Comment by mikepenz** [comment] 2016-04-22 23:19
@toastking42 the new version is already released. 

weird I tried exactly your steps, but didn't see it. might forcing the recreation of the items of the `MiniDrawer` will help?
