### ISSUE TITLE
Drawer still shows old items after using setItems

### ISSUE THREAD

**Issue by fdorssers** [mikepenz/MaterialDrawer#70] opened 2015-03-06 09:49 UTC
I've been working on getting the logging in and logging out working in my app. After the user presses the log out button in the drawer a bunch of items should be removed. This is done by basically determining which items are still relevant and setting these in the drawer. This all happens in the same activity so completely remaking the drawer wouldn't be optimal. I'm using the following function to reset the information:
```Java
public void resetDrawer() {
    ArrayList<IProfile> profileItems = getProfileItems();
    mAccountHeader.setProfiles(profileItems);

    ArrayList<IDrawerItem> items = getItems();
    Log.d(TAG, "Setting #items: " + items.size());
    items.add(new PrimaryDrawerItem().withName("Settings").withIcon(FontAwesome.Icon.faw_cog).withIdentifier(SETTINGS_ID).withCheckable(false));
    mDrawer.setItems(items);
}
```
Resetting the profiles works fine, however after resetting the drawer items I still see about 14 items opposed to the 3 items that the log function says have been added. If I then remake the activity it only shows the relevant three. So it seems something goes wrong in the `setItems()` function. Maybe when notifying the adapter of changes or something.

**Comment by mikepenz** [comment] 2015-03-06 12:31
@fdorssers at which time do you call this method? can it happen that this method is called when the drawer still shows the ProfileItems?

i can't reproduce this issue :/

**Comment by fdorssers** [comment] 2015-03-06 13:37
Ah, that's probably it! I've got the following `OnAccountHeaderClickListener` on the account header:
```Java
@Override
public void onSelectionClick(IProfile currentProfile) {
    if (currentProfile instanceof IDrawerItem && ((IDrawerItem) currentProfile).getIdentifier() == LOGIN_ID) {
        // ...
    } else if (currentProfile instanceof IDrawerItem && ((IDrawerItem) currentProfile).getIdentifier() == LOGOUT_ID) {
        // ...
        resetDrawer();
    }
}
```
So the drawer items are changed while the profile items are still shown. Meaning that once the on click is processed the original items, which were copied from the drawer before, are set back. I should now be able to create a simple example application which shows this issue, if you want.

**Comment by mikepenz** [comment] 2015-03-06 16:02
@fdorssers i've changed some things regarding this. perhaps it already solved your issue. will publish v2.0.0 today. If this issue is still there i'll try to create a workaround for this ;)

**Comment by mikepenz** [comment] 2015-03-06 19:27
Reopen if it's not fixed with v2.0.0. Did some tests and i hope if solved this.

**Closed** 2015-03-06 19:27 UTC
Labels: bug

**Comment by fdorssers** [comment] 2015-03-06 19:57
Works like a charm now, thanks!

**Comment by mikepenz** [comment] 2015-03-06 19:59
@fdorssers awesome :). was not sure if it was the fix but yeah :)

Thank you so much for all your help testing all new features.
