### ISSUE TITLE
OutofMemory exception

### ISSUE THREAD

**Issue by vj12354** [mikepenz/MaterialDrawer#1142] opened 2016-03-30 17:22 UTC
I had a quick run of your sample app, from 'master' branch. Firstly, it look great and you did a good job. But it looks to be very memory intensive and would need clean of objects.

Steps to reproduce:
1. launch the sample app
2. press back button ( optionally, open navigation drawer)
3. Again, relaunch the app
4. Repeat Steps (1-3) for around seven / eight times and you will hit OutOfMemoryException

Note: Keep an eye on the memory in the Android monitor view, which keeps on increasing constantly.

```
03-30 18:07:57.400 30578-30578/com.mikepenz.materialdrawer.app.debug D/OpenGLRenderer: Enabling debug mode 0
03-30 18:08:35.845 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm-heap: Clamp target GC heap from 65.572MB to 64.000MB
03-30 18:08:41.800 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm-heap: Clamp target GC heap from 70.950MB to 64.000MB
03-30 18:08:41.800 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm-heap: Forcing collection of SoftReferences for 2359312-byte allocation
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm-heap: Clamp target GC heap from 69.061MB to 64.000MB
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug D/dalvikvm: GC_BEFORE_OOM freed 1997K, 5% free 61682K/64464K, paused 73ms, total 73ms
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug E/dalvikvm-heap: Out of memory on a 2359312-byte allocation.
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm: "main" prio=5 tid=1 RUNNABLE
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x41dfed08 self=0x41deb7a0
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:   | sysTid=30578 nice=-11 sched=0/0 cgrp=apps handle=1074749780
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:   | state=R schedstat=( 4070656829 313919319 2169 ) utm=348 stm=58 core=1
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:701)
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:526)
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:889)
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.content.res.Resources.loadDrawable(Resources.java:3453)
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.content.res.Resources.getDrawable(Resources.java:1893)
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:55)
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:391)
03-30 18:08:41.875 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.support.v7.widget.TintResources.getDrawable(TintResources.java:48)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:66)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:71)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at com.mikepenz.materialdrawer.holder.ImageHolder.applyTo(ImageHolder.java:79)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at com.mikepenz.materialize.holder.ImageHolder.applyTo(ImageHolder.java:171)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:808)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at com.mikepenz.materialdrawer.app.DrawerActivity.onCreate(DrawerActivity.java:72)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.app.Activity.performCreate(Activity.java:5582)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2405)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2500)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.app.ActivityThread.access$900(ActivityThread.java:171)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.os.Looper.loop(Looper.java:146)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at android.app.ActivityThread.main(ActivityThread.java:5679)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:515)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug I/dalvikvm:     at dalvik.system.NativeStart.main(Native Method)
03-30 18:08:41.880 30578-30578/com.mikepenz.materialdrawer.app.debug D/skia: --- allocation failed for scaled bitmap
03-30 18:08:41.885 30578-30578/com.mikepenz.materialdrawer.app.debug D/AndroidRuntime: Shutting down VM
03-30 18:08:41.885 30578-30578/com.mikepenz.materialdrawer.app.debug W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41dfdc08)
03-30 18:08:41.890 30578-30578/com.mikepenz.materialdrawer.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: com.mikepenz.materialdrawer.app.debug, PID: 30578
                                                                                       java.lang.OutOfMemoryError
                                                                                           at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                                           at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:701)
                                                                                           at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:526)
                                                                                           at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:889)
                                                                                           at android.content.res.Resources.loadDrawable(Resources.java:3453)
                                                                                           at android.content.res.Resources.getDrawable(Resources.java:1893)
                                                                                           at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:55)
                                                                                           at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:391)
                                                                                           at android.support.v7.widget.TintResources.getDrawable(TintResources.java:48)
                                                                                           at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
                                                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                                                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                                           at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:66)
                                                                                           at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:71)
                                                                                           at com.mikepenz.materialdrawer.holder.ImageHolder.applyTo(ImageHolder.java:79)
                                                                                           at com.mikepenz.materialize.holder.ImageHolder.applyTo(ImageHolder.java:171)
                                                                                           at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:808)
                                                                                           at com.mikepenz.materialdrawer.app.DrawerActivity.onCreate(DrawerActivity.java:72)
                                                                                           at android.app.Activity.performCreate(Activity.java:5582)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2405)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2500)
                                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:171)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:146)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5679)
                                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                                           at dalvik.system.NativeStart.main(Native Method)
03-30 18:08:43.890 30578-30578/com.mikepenz.materialdrawer.app.debug I/Process: Sending signal. PID: 30578 SIG: 9
```

**Comment by mikepenz** [comment] 2016-03-30 17:40
@vj12354 just tried the same. Stopped after 30 times opening and closing. No `OutOfMemory` was thrown. 

Also I do not see the reference to the `MaterialDrawer` as the exception is thrown by system default methods. 

```java
.setImageResource(AppCompatImageView.java:71)
```

I am not sure how loading an image by `ressource-identifier` could be optimized on the `MaterialDrawer` side.

**Comment by vj12354** [comment] 2016-03-30 19:24
@mikepenz Have you noticed any memory usage spiking up each time you close (pressing back button) and reopen the app ?

On Samsung S3 the OOM exception occurs after 12 times.

**Comment by mikepenz** [comment] 2016-03-30 19:44
@vj12354 no haven'T noticed anything. Just the normal spikes when I close the activity that it clears RAM as the application is no longer active with the back button, and normal re-allocating when the app starts again. 

I tried it with a Nexus 6P (30 launches of the MaterialDrawer), with a Nexus 6 (30 launches of the MaterialDrawer), and with a Nexus 5 (50 launches of the MaterialDrawer). Was not able to get an OOM in any of those cases. 

I also tried to find a possible leak with https://github.com/square/leakcanary but no leak detected. I launched the app many many times on my Nexus 5, navigated through all different sample activities, closed, opened, turned, clicked. Was not able to detect any leak. 

Perhaps there's a leak with the support libraries v23.2.1 and samsung?

**Comment by stargie** [comment] 2016-04-05 11:04
Same problem here.
I have BaseActivity where i setup drawer and all my activites extend BaseActivity and after 5-6 jumps between activities i got OutOfMemery exception.
I'am testing app on device API19 Android 4.4.4 Samsung Galaxy Alpha
I noticed that error occurs on AccountHeaderBuilder. Code below throws error.

AccountHeader drawerHeader = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.drawer_header_backgroud)
                .withSelectionListEnabledForSingleProfile(false)
                .withProfileImagesVisible(false)
                .addProfiles(profile).build();

04-05 12:47:12.243 27277-27277/com.stg.test E/dalvikvm-heap: Out of memory on a 2880016-byte allocation.
04-05 12:47:12.258 27277-27277/com.stg.test E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.stg.test, PID: 27277
                                                                           java.lang.OutOfMemoryError
                                                                               at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                               at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:701)
                                                                               at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:526)
                                                                               at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:889)
                                                                               at android.content.res.Resources.loadDrawable(Resources.java:3453)
                                                                               at android.content.res.Resources.getDrawable(Resources.java:1893)
                                                                               at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:55)
                                                                               at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:391)
                                                                               at android.support.v7.widget.TintResources.getDrawable(TintResources.java:48)
                                                                               at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
                                                                               at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                                                                               at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                               at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:66)
                                                                               at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:71)
                                                                               at com.mikepenz.materialdrawer.holder.ImageHolder.applyTo(ImageHolder.java:79)
                                                                               at com.mikepenz.materialize.holder.ImageHolder.applyTo(ImageHolder.java:171)
                                                                               at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:808)
                                                                               at com.stg.test.BaseActivity.setUpNavigationDrawer(BaseActivity.java:69)
                                                                               at com.stg.test.MainActivity.onCreate(MainActivity.java:61)
                                                                               at android.app.Activity.performCreate(Activity.java:5585)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
                                                                               at android.app.ActivityThread.access$900(ActivityThread.java:170)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:146)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5635)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                               at dalvik.system.NativeStart.main(Native Method)

**Comment by ibrahim132** [comment] 2016-04-05 11:33
Also i have the same error on Samsung Galaxy Note 2 (GT N7100) Android version 4.4.2

**Comment by mikepenz** [comment] 2016-04-05 11:35
@vj12354 @stargie @ibrahim132 someone might create a sample application to showcase this issue

**Comment by vj12354** [comment] 2016-04-05 17:04
@mikepenz I have just testing on latest code v5.1.8 and looks like it the sample app has improved in terms of memory management. But I still get the OOM exception in my sample app, as the memory gets spiking up after hopping between 8-10 screens. Also the frequency is high if I use profile pics.

**Comment by mikepenz** [comment] 2016-04-05 17:07
@vj12354 I have enabled leak canary which would detect leaks caused by the lib. There are non. The issue itself is also thrown by a function I can not control. We just set an image via it's ressource identifier which is an `int`. So nothing I can improve here. 

I really tried it on all my phones. Including an old Nexus 5. But after 50 tried opening closing, or navigating through the sample app about 50 times I stopped because nothing bad happened.

**Comment by mikepenz** [comment] 2016-04-09 11:32
With more research into this issue, I still was not able to get a `OOM` on my side. I only see normal memory usage. When switching to the profile list the first time it will need some more memory because the image loading library downloads the images and caches them in the ram. If I remove the images which are loaded from the web, there is just a tiny usage of memory for the switching of the list, but nothing which could result in an `OOM`

**Comment by mikepenz** [comment] 2016-04-14 12:26
Please also see the following answer:
https://github.com/mikepenz/MaterialDrawer/issues/1181

**Comment by mikepenz** [comment] 2016-04-15 14:52
```java
public class DrawerImageLoader implements DrawerImageLoader.IDrawerImageLoader {
    @Override
    public void set(ImageView imageView, Uri uri, Drawable placeholder) {
        try {
... we set the high res image and see if its fine
} catch (OutOfMemoryError outOfMemoryError) {
... we want to set some smaller image or just a color
}
    }

    @Override
    public void cancel(ImageView imageView) {
    }

    @Override
    public Drawable placeholder(Context ctx) {
        return DrawerUIUtils.getPlaceHolder(ctx);
    }

    @Override
    public Drawable placeholder(Context ctx, String tag) {
        return placeholder(ctx);
    }
}
```

**Closed by mikepenz** 2016-04-15 14:52 UTC
Labels: invalid

**Comment by inteist** [comment] 2017-05-30 13:46
I have just integrated the library into my app and although I have not had any issues while developing and testing, I get this on about half the devices 


```
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:587)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:422)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
	at android.content.res.Resources.loadDrawable(Resources.java:2150)
	at android.content.res.Resources.getDrawable(Resources.java:715)
	at android.support.v7.widget.VectorEnabledTintResources.a(VectorEnabledTintResources.java:74)
	at android.support.v7.widget.AppCompatDrawableManager.a(AppCompatDrawableManager.java:437)
	at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:67)
	at android.support.v4.content.b.getDrawable(ContextCompat.java:374)
	at android.support.v7.widget.AppCompatDrawableManager.a(AppCompatDrawableManager.java:202)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
	at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
	at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:73)
	at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:81)
	at com.mikepenz.materialdrawer.a.d.a(ImageHolder.java:79)
	at com.mikepenz.materialize.b.c.a(ImageHolder.java:172)
	at com.mikepenz.materialdrawer.b.a(AccountHeaderBuilder.java:809)
```

I use android drawables for the menu icons and a 120K jpeg for the drawer header background
with CENTER_CROP 
 .withHeaderBackgroundScaleType(ImageView.ScaleType.CENTER_CROP)

no other changes were made to the app and the problem is obviously coming from the drawer based on the stacktrace.
