### ISSUE TITLE
Screen moves about 100 pixeles down with version 6.0.9

### ISSUE THREAD

**Issue by AlanFloyd** [mikepenz/MaterialDrawer#2567] opened 2020-03-03 15:59 UTC
After migrating to the version 6.0.9 (at this moment I don't want to migrate to the latest version) I see that the screen of all my activities are moving around 100 pixeles down. 

When not using the version, the screen is perfect shown, as it was designed.

Is there any configuration that can be changed so the the screen starts on top?

I used before 4.6.0 and it was fine there. But with this version I have the issue that on Android 10, calling the drawer, will crash the app.

Greetings and thanks
Dietmar

**Comment by mikepenz** [comment] 2020-03-03 17:33
@AlanFloyd could it be that there is some fitsSystemWindow flag used somewhere where it shouldn't be? sounds like a insetting topic

**Comment by AlanFloyd** [comment] 2020-03-03 17:58
No. Even forcing with  :

  View view = findViewById(R.id.noticias);
        view.setFitsSystemWindows(false);
        view.setPadding(0, 0, 0, 0);

doesn't change the behavior.

**Comment by AlanFloyd** [comment] 2020-03-03 18:12
It looks like that the ActionBar is shown, even that I hide it in the app

ActionBar actionBar = getSupportActionBar();
actionBar.hide();
 
Without hiding, the name of the app is shown, hiding shows nothing. but the space stays.

**Comment by mikepenz** [comment] 2020-03-08 11:23
You really should use a `Toolbar` for this matter as `ActionBar`s will lead to all sorts of strange behaviors . 

And if you have the toolbar you will be able to set the full toolbar to gone. 

As far as I can say this shouldn't be an issue of the library and works as expected

**Comment by mikepenz** [comment] 2020-03-22 15:07
@AlanFloyd were you able to resolve it?

I believe this can be closed as it is not directly caused by the library, but more related to the used layout. 

Please also consider using v8 which will do away with any fit system flags custom handling and fully give all control with the `DrawerLayout` to you

**Closed by mikepenz** 2020-03-22 15:07 UTC
Labels: unrelated
